package httpx_test

import "testing"

func TestFrameworkHTTPUpstreamInventoryCoverage(t *testing.T) {
	ported := []string{
		"HttpClientTest::testStubbedResponsesAreReturnedAfterFaking",                                                                // Port of HttpClientTest::testStubbedResponsesAreReturnedAfterFaking
		"HttpClientTest::testCreatedRequest",                                                                                        // Port of HttpClientTest::testCreatedRequest
		"HttpClientTest::testStatusCodeShorthand",                                                                                   // Port of HttpClientTest::testStatusCodeShorthand
		"HttpClientTest::testStatusCodeShorthandAssumeBodyWhenInvalidHttpStatusCode",                                                // Port of HttpClientTest::testStatusCodeShorthandAssumeBodyWhenInvalidHttpStatusCode
		"HttpClientTest::testBodyShorthands",                                                                                        // Port of HttpClientTest::testBodyShorthands
		"HttpClientTest::testAcceptedRequest",                                                                                       // Port of HttpClientTest::testAcceptedRequest
		"HttpClientTest::testMovedPermanentlyRequest",                                                                               // Port of HttpClientTest::testMovedPermanentlyRequest
		"HttpClientTest::testNoContentRequest",                                                                                      // Port of HttpClientTest::testNoContentRequest
		"HttpClientTest::testFoundRequest",                                                                                          // Port of HttpClientTest::testFoundRequest
		"HttpClientTest::testNotModifiedRequest",                                                                                    // Port of HttpClientTest::testNotModifiedRequest
		"HttpClientTest::testBadRequestRequest",                                                                                     // Port of HttpClientTest::testBadRequestRequest
		"HttpClientTest::testPaymentRequiredRequest",                                                                                // Port of HttpClientTest::testPaymentRequiredRequest
		"HttpClientTest::testRequestTimeoutRequest",                                                                                 // Port of HttpClientTest::testRequestTimeoutRequest
		"HttpClientTest::testConflictResponseRequest",                                                                               // Port of HttpClientTest::testConflictResponseRequest
		"HttpClientTest::testUnprocessableContentRequest",                                                                           // Port of HttpClientTest::testUnprocessableContentRequest
		"HttpClientTest::testUnprocessableEntityRequest",                                                                            // Port of HttpClientTest::testUnprocessableEntityRequest
		"HttpClientTest::testTooManyRequestsRequest",                                                                                // Port of HttpClientTest::testTooManyRequestsRequest
		"HttpClientTest::testUnauthorizedRequest",                                                                                   // Port of HttpClientTest::testUnauthorizedRequest
		"HttpClientTest::testForbiddenRequest",                                                                                      // Port of HttpClientTest::testForbiddenRequest
		"HttpClientTest::testNotFoundResponse",                                                                                      // Port of HttpClientTest::testNotFoundResponse
		"HttpClientTest::testResponseBodyCasting",                                                                                   // Port of HttpClientTest::testResponseBodyCasting
		"HttpClientTest::testResponseObjectAsArray",                                                                                 // Port of HttpClientTest::testResponseObjectAsArray
		"HttpClientTest::testResponseObjectAsObject",                                                                                // Port of HttpClientTest::testResponseObjectAsObject
		"HttpClientTest::testResponseObjectIsTappable",                                                                              // Port of HttpClientTest::testResponseObjectIsTappable
		"HttpClientTest::testResponseObjectIsMacroable",                                                                             // Port of HttpClientTest::testResponseObjectIsMacroable
		"HttpClientTest::testResponseCanBeReturnedAsResource",                                                                       // Port of HttpClientTest::testResponseCanBeReturnedAsResource
		"HttpClientTest::testResponseCanBeReturnedAsCollection",                                                                     // Port of HttpClientTest::testResponseCanBeReturnedAsCollection
		"HttpClientTest::testResponseCanBeReturnedAsFluent",                                                                         // Port of HttpClientTest::testResponseCanBeReturnedAsFluent
		"HttpClientTest::testSendRequestBodyAsJsonByDefault",                                                                        // Port of HttpClientTest::testSendRequestBodyAsJsonByDefault
		"HttpClientTest::testSendRequestBodyWithManyAmpersands",                                                                     // Port of HttpClientTest::testSendRequestBodyWithManyAmpersands
		"HttpClientTest::testSendStreamRequestBody",                                                                                 // Port of HttpClientTest::testSendStreamRequestBody
		"HttpClientTest::testUrlsCanBeStubbedByPath",                                                                                // Port of HttpClientTest::testUrlsCanBeStubbedByPath
		"HttpClientTest::testCanSendJsonData",                                                                                       // Port of HttpClientTest::testCanSendJsonData
		"HttpClientTest::testCanSendFormData",                                                                                       // Port of HttpClientTest::testCanSendFormData
		"HttpClientTest::testCanSendArrayableFormData",                                                                              // Port of HttpClientTest::testCanSendArrayableFormData
		"HttpClientTest::testCanSendJsonSerializableData",                                                                           // Port of HttpClientTest::testCanSendJsonSerializableData
		"HttpClientTest::testPrefersJsonSerializableOverArrayableData",                                                              // Port of HttpClientTest::testPrefersJsonSerializableOverArrayableData
		"HttpClientTest::testCanSendJsonDataWithStringable",                                                                         // Port of HttpClientTest::testCanSendJsonDataWithStringable
		"HttpClientTest::testCanSendFormDataWithStringable",                                                                         // Port of HttpClientTest::testCanSendFormDataWithStringable
		"HttpClientTest::testCanSendFormDataWithStringableInArrays",                                                                 // Port of HttpClientTest::testCanSendFormDataWithStringableInArrays
		"HttpClientTest::testRecordedCallsAreEmptiedWhenFakeIsCalled",                                                               // Port of HttpClientTest::testRecordedCallsAreEmptiedWhenFakeIsCalled
		"HttpClientTest::testSpecificRequestIsNotBeingSent",                                                                         // Port of HttpClientTest::testSpecificRequestIsNotBeingSent
		"HttpClientTest::testNoRequestIsNotBeingSent",                                                                               // Port of HttpClientTest::testNoRequestIsNotBeingSent
		"HttpClientTest::testRequestCount",                                                                                          // Port of HttpClientTest::testRequestCount
		"HttpClientTest::testCanSendMultipartData",                                                                                  // Port of HttpClientTest::testCanSendMultipartData
		"HttpClientTest::testFilesCanBeAttached",                                                                                    // Port of HttpClientTest::testFilesCanBeAttached
		"HttpClientTest::testCanSendMultipartDataWithSimplifiedParameters",                                                          // Port of HttpClientTest::testCanSendMultipartDataWithSimplifiedParameters
		"HttpClientTest::testCanSendMultipartDataWithBothSimplifiedAndExtendedParameters",                                           // Port of HttpClientTest::testCanSendMultipartDataWithBothSimplifiedAndExtendedParameters
		"HttpClientTest::testCanSendMultipartDataWithArrayValues",                                                                   // Port of HttpClientTest::testCanSendMultipartDataWithArrayValues
		"HttpClientTest::testCanSendMultipartDataWithFileAndArrayValues",                                                            // Port of HttpClientTest::testCanSendMultipartDataWithFileAndArrayValues
		"HttpClientTest::testItCanSendToken",                                                                                        // Port of HttpClientTest::testItCanSendToken
		"HttpClientTest::testItCanSendUserAgent",                                                                                    // Port of HttpClientTest::testItCanSendUserAgent
		"HttpClientTest::testItOnlySendsOneUserAgentHeader",                                                                         // Port of HttpClientTest::testItOnlySendsOneUserAgentHeader
		"HttpClientTest::testSequenceBuilder",                                                                                       // Port of HttpClientTest::testSequenceBuilder
		"HttpClientTest::testSequenceBuilderCanKeepGoingWhenEmpty",                                                                  // Port of HttpClientTest::testSequenceBuilderCanKeepGoingWhenEmpty
		"HttpClientTest::testAssertSequencesAreEmpty",                                                                               // Port of HttpClientTest::testAssertSequencesAreEmpty
		"HttpClientTest::testFakeSequence",                                                                                          // Port of HttpClientTest::testFakeSequence
		"HttpClientTest::testWithCookies",                                                                                           // Port of HttpClientTest::testWithCookies
		"HttpClientTest::testWithQueryParameters",                                                                                   // Port of HttpClientTest::testWithQueryParameters
		"HttpClientTest::testWithArrayQueryParameters",                                                                              // Port of HttpClientTest::testWithArrayQueryParameters
		"HttpClientTest::testWithQueryParametersAllowsAddingMoreOnRequest",                                                          // Port of HttpClientTest::testWithQueryParametersAllowsAddingMoreOnRequest
		"HttpClientTest::testWithQueryParametersAllowsOverridingParameterOnRequest",                                                 // Port of HttpClientTest::testWithQueryParametersAllowsOverridingParameterOnRequest
		"HttpClientTest::testWithStringableQueryParameters",                                                                         // Port of HttpClientTest::testWithStringableQueryParameters
		"HttpClientTest::testWithArrayStringableQueryParameters",                                                                    // Port of HttpClientTest::testWithArrayStringableQueryParameters
		"HttpClientTest::testGetWithArrayQueryParam",                                                                                // Port of HttpClientTest::testGetWithArrayQueryParam
		"HttpClientTest::testGetWithArrayableQueryParam",                                                                            // Port of HttpClientTest::testGetWithArrayableQueryParam
		"HttpClientTest::testGetWithStringQueryParam",                                                                               // Port of HttpClientTest::testGetWithStringQueryParam
		"HttpClientTest::testGetWithQuery",                                                                                          // Port of HttpClientTest::testGetWithQuery
		"HttpClientTest::testGetWithQueryWontEncode",                                                                                // Port of HttpClientTest::testGetWithQueryWontEncode
		"HttpClientTest::testGetWithArrayQueryParamOverwrites",                                                                      // Port of HttpClientTest::testGetWithArrayQueryParamOverwrites
		"HttpClientTest::testGetWithArrayQueryParamEncodes",                                                                         // Port of HttpClientTest::testGetWithArrayQueryParamEncodes
		"HttpClientTest::testWithBaseUrl",                                                                                           // Port of HttpClientTest::testWithBaseUrl
		"HttpClientTest::testCanConfirmManyHeaders",                                                                                 // Port of HttpClientTest::testCanConfirmManyHeaders
		"HttpClientTest::testCanConfirmManyHeadersUsingAString",                                                                     // Port of HttpClientTest::testCanConfirmManyHeadersUsingAString
		"HttpClientTest::testItMergesMultipleHeaders",                                                                               // Port of HttpClientTest::testItMergesMultipleHeaders
		"HttpClientTest::testItCanReplaceHeaders",                                                                                   // Port of HttpClientTest::testItCanReplaceHeaders
		"HttpClientTest::testItCanReplaceHeadersWhenNoHeadersYetSet",                                                                // Port of HttpClientTest::testItCanReplaceHeadersWhenNoHeadersYetSet
		"HttpClientTest::testCanConfirmSingleStringHeader",                                                                          // Port of HttpClientTest::testCanConfirmSingleStringHeader
		"HttpClientTest::testCanConfirmSingleArrayHeader",                                                                           // Port of HttpClientTest::testCanConfirmSingleArrayHeader
		"HttpClientTest::testExceptionAccessorOnSuccess",                                                                            // Port of HttpClientTest::testExceptionAccessorOnSuccess
		"HttpClientTest::testExceptionAccessorOnFailure",                                                                            // Port of HttpClientTest::testExceptionAccessorOnFailure
		"HttpClientTest::testRequestExceptionSummary",                                                                               // Port of HttpClientTest::testRequestExceptionSummary
		"HttpClientTest::testRequestExceptionTruncatedSummary",                                                                      // Port of HttpClientTest::testRequestExceptionTruncatedSummary
		"HttpClientTest::testRequestExceptionWithoutTruncatedSummary",                                                               // Port of HttpClientTest::testRequestExceptionWithoutTruncatedSummary
		"HttpClientTest::testRequestExceptionWithCustomTruncatedSummary",                                                            // Port of HttpClientTest::testRequestExceptionWithCustomTruncatedSummary
		"HttpClientTest::testRequestLevelTruncationLevelOnRequestException",                                                         // Port of HttpClientTest::testRequestLevelTruncationLevelOnRequestException
		"HttpClientTest::testNoTruncationOnRequestLevel",                                                                            // Port of HttpClientTest::testNoTruncationOnRequestLevel
		"HttpClientTest::testRequestExceptionDoesNotTruncateButRequestDoes",                                                         // Port of HttpClientTest::testRequestExceptionDoesNotTruncateButRequestDoes
		"HttpClientTest::testAsyncRequestExceptionsRespectRequestTruncation",                                                        // Port of HttpClientTest::testAsyncRequestExceptionsRespectRequestTruncation
		"HttpClientTest::testRequestExceptionEmptyBody",                                                                             // Port of HttpClientTest::testRequestExceptionEmptyBody
		"HttpClientTest::testReportingExceptionTwiceDoesNotIncludeSummaryTwice",                                                     // Port of HttpClientTest::testReportingExceptionTwiceDoesNotIncludeSummaryTwice
		"HttpClientTest::testStreamingResponseExceptionMessageIsNotSummarizedWhenBodyIsNotSeekable",                                 // Port of HttpClientTest::testStreamingResponseExceptionMessageIsNotSummarizedWhenBodyIsNotSeekable
		"HttpClientTest::testOnErrorDoesntCallClosureOnInformational",                                                               // Port of HttpClientTest::testOnErrorDoesntCallClosureOnInformational
		"HttpClientTest::testOnErrorDoesntCallClosureOnSuccess",                                                                     // Port of HttpClientTest::testOnErrorDoesntCallClosureOnSuccess
		"HttpClientTest::testOnErrorDoesntCallClosureOnRedirection",                                                                 // Port of HttpClientTest::testOnErrorDoesntCallClosureOnRedirection
		"HttpClientTest::testOnErrorCallsClosureOnClientError",                                                                      // Port of HttpClientTest::testOnErrorCallsClosureOnClientError
		"HttpClientTest::testOnErrorCallsClosureOnServerError",                                                                      // Port of HttpClientTest::testOnErrorCallsClosureOnServerError
		"HttpClientTest::testSinkToFile",                                                                                            // Port of HttpClientTest::testSinkToFile
		"HttpClientTest::testSinkToResource",                                                                                        // Port of HttpClientTest::testSinkToResource
		"HttpClientTest::testSinkWhenStubbedByPath",                                                                                 // Port of HttpClientTest::testSinkWhenStubbedByPath
		"HttpClientTest::testCanAssertAgainstOrderOfHttpRequestsWithUrlStrings",                                                     // Port of HttpClientTest::testCanAssertAgainstOrderOfHttpRequestsWithUrlStrings
		"HttpClientTest::testAssertionsSentOutOfOrderThrowAssertionFailed",                                                          // Port of HttpClientTest::testAssertionsSentOutOfOrderThrowAssertionFailed
		"HttpClientTest::testWrongNumberOfRequestsThrowAssertionFailed",                                                             // Port of HttpClientTest::testWrongNumberOfRequestsThrowAssertionFailed
		"HttpClientTest::testCanAssertAgainstOrderOfHttpRequestsWithCallables",                                                      // Port of HttpClientTest::testCanAssertAgainstOrderOfHttpRequestsWithCallables
		"HttpClientTest::testCanAssertAgainstOrderOfHttpRequestsWithCallablesAndHeaders",                                            // Port of HttpClientTest::testCanAssertAgainstOrderOfHttpRequestsWithCallablesAndHeaders
		"HttpClientTest::testCanAssertAgainstOrderOfHttpRequestsWithCallablesAndHeadersFailsCorrectly",                              // Port of HttpClientTest::testCanAssertAgainstOrderOfHttpRequestsWithCallablesAndHeadersFailsCorrectly
		"HttpClientTest::testCanDump",                                                                                               // Port of HttpClientTest::testCanDump
		"HttpClientTest::testResponseCanDump",                                                                                       // Port of HttpClientTest::testResponseCanDump
		"HttpClientTest::testResponseCanDumpWithKey",                                                                                // Port of HttpClientTest::testResponseCanDumpWithKey
		"HttpClientTest::testResponseCanDumpHeaders",                                                                                // Port of HttpClientTest::testResponseCanDumpHeaders
		"HttpClientTest::testResponseSequenceIsMacroable",                                                                           // Port of HttpClientTest::testResponseSequenceIsMacroable
		"HttpClientTest::testRequestsCanBeAsync",                                                                                    // Port of HttpClientTest::testRequestsCanBeAsync
		"HttpClientTest::testClientCanBeSet",                                                                                        // Port of HttpClientTest::testClientCanBeSet
		"HttpClientTest::testRequestsCanReplaceOptions",                                                                             // Port of HttpClientTest::testRequestsCanReplaceOptions
		"HttpClientTest::testMultipleRequestsAreSentInThePool",                                                                      // Port of HttpClientTest::testMultipleRequestsAreSentInThePool
		"HttpClientTest::testMultipleRequestsAreSentInThePoolWithKeys",                                                              // Port of HttpClientTest::testMultipleRequestsAreSentInThePoolWithKeys
		"HttpClientTest::testMiddlewareRunsInPool",                                                                                  // Port of HttpClientTest::testMiddlewareRunsInPool
		"HttpClientTest::testPoolConcurrency",                                                                                       // Port of HttpClientTest::testPoolConcurrency
		"HttpClientTest::testTheRequestSendingAndResponseReceivedEventsAreFiredWhenARequestIsSent",                                  // Port of HttpClientTest::testTheRequestSendingAndResponseReceivedEventsAreFiredWhenARequestIsSent
		"HttpClientTest::testTheRequestSendingAndResponseReceivedEventsAreFiredWhenARequestIsSentAsync",                             // Port of HttpClientTest::testTheRequestSendingAndResponseReceivedEventsAreFiredWhenARequestIsSentAsync
		"HttpClientTest::testTheRequestSendingAndResponseReceivedEventsAreFiredForEveryRetry",                                       // Port of HttpClientTest::testTheRequestSendingAndResponseReceivedEventsAreFiredForEveryRetry
		"HttpClientTest::testTheTransferStatsAreCalledSafelyWhenFakingTheRequest",                                                   // Port of HttpClientTest::testTheTransferStatsAreCalledSafelyWhenFakingTheRequest
		"HttpClientTest::testTransferStatsArePresentWhenFakingTheRequestUsingAPromiseResponse",                                      // Port of HttpClientTest::testTransferStatsArePresentWhenFakingTheRequestUsingAPromiseResponse
		"HttpClientTest::testClonedClientsWorkSuccessfullyWithTheRequestObject",                                                     // Port of HttpClientTest::testClonedClientsWorkSuccessfullyWithTheRequestObject
		"HttpClientTest::testRequestIsMacroable",                                                                                    // Port of HttpClientTest::testRequestIsMacroable
		"HttpClientTest::testRequestExceptionIsThrownWhenRetriesExhausted",                                                          // Port of HttpClientTest::testRequestExceptionIsThrownWhenRetriesExhausted
		"HttpClientTest::testRequestExceptionIsThrownWhenRetriesExhaustedWithBackoffArray",                                          // Port of HttpClientTest::testRequestExceptionIsThrownWhenRetriesExhaustedWithBackoffArray
		"HttpClientTest::testRequestExceptionIsThrownWithoutRetriesIfRetryNotNecessary",                                             // Port of HttpClientTest::testRequestExceptionIsThrownWithoutRetriesIfRetryNotNecessary
		"HttpClientTest::testRequestExceptionIsThrownWithoutRetriesIfRetryNotNecessaryWithBackoffArray",                             // Port of HttpClientTest::testRequestExceptionIsThrownWithoutRetriesIfRetryNotNecessaryWithBackoffArray
		"HttpClientTest::testRequestExceptionIsNotThrownWhenDisabledAndRetriesExhausted",                                            // Port of HttpClientTest::testRequestExceptionIsNotThrownWhenDisabledAndRetriesExhausted
		"HttpClientTest::testRequestExceptionIsNotThrownWhenDisabledAndRetriesExhaustedWithBackoffArray",                            // Port of HttpClientTest::testRequestExceptionIsNotThrownWhenDisabledAndRetriesExhaustedWithBackoffArray
		"HttpClientTest::testRequestExceptionIsNotThrownWithoutRetriesIfRetryNotNecessary",                                          // Port of HttpClientTest::testRequestExceptionIsNotThrownWithoutRetriesIfRetryNotNecessary
		"HttpClientTest::testRequestExceptionIsNotThrownWithoutRetriesIfRetryNotNecessaryWithBackoffArray",                          // Port of HttpClientTest::testRequestExceptionIsNotThrownWithoutRetriesIfRetryNotNecessaryWithBackoffArray
		"HttpClientTest::testRequestCanBeModifiedInRetryCallback",                                                                   // Port of HttpClientTest::testRequestCanBeModifiedInRetryCallback
		"HttpClientTest::testRequestCanBeModifiedInRetryCallbackWithBackoffArray",                                                   // Port of HttpClientTest::testRequestCanBeModifiedInRetryCallbackWithBackoffArray
		"HttpClientTest::testExceptionThrownInRetryCallbackWithoutRetrying",                                                         // Port of HttpClientTest::testExceptionThrownInRetryCallbackWithoutRetrying
		"HttpClientTest::testExceptionThrownInRetryCallbackWithoutRetryingWithBackoffArray",                                         // Port of HttpClientTest::testExceptionThrownInRetryCallbackWithoutRetryingWithBackoffArray
		"HttpClientTest::testRequestsWillBeWaitingSleepMillisecondsReceivedBeforeRetry",                                             // Port of HttpClientTest::testRequestsWillBeWaitingSleepMillisecondsReceivedBeforeRetry
		"HttpClientTest::testRequestExceptionReturnedWhenRetriesExhaustedInPool",                                                    // Port of HttpClientTest::testRequestExceptionReturnedWhenRetriesExhaustedInPool
		"HttpClientTest::testRequestExceptionIsReturnedWithoutRetriesIfRetryNotNecessaryInPool",                                     // Port of HttpClientTest::testRequestExceptionIsReturnedWithoutRetriesIfRetryNotNecessaryInPool
		"HttpClientTest::testRequestExceptionIsNotReturnedWhenDisabledAndRetriesExhaustedInPool",                                    // Port of HttpClientTest::testRequestExceptionIsNotReturnedWhenDisabledAndRetriesExhaustedInPool
		"HttpClientTest::testRequestExceptionIsNotReturnedWithoutRetriesIfRetryNotNecessaryInPool",                                  // Port of HttpClientTest::testRequestExceptionIsNotReturnedWithoutRetriesIfRetryNotNecessaryInPool
		"HttpClientTest::testRequestCanBeModifiedInRetryCallbackInPool",                                                             // Port of HttpClientTest::testRequestCanBeModifiedInRetryCallbackInPool
		"HttpClientTest::testHandleRequestExeptionWithNoResponseInPoolConsideredConnectionException",                                // Port of HttpClientTest::testHandleRequestExeptionWithNoResponseInPoolConsideredConnectionException
		"HttpClientTest::testExceptionThrownInRetryCallbackIsReturnedWithoutRetryingInPool",                                         // Port of HttpClientTest::testExceptionThrownInRetryCallbackIsReturnedWithoutRetryingInPool
		"HttpClientTest::testExceptionThrowInMiddlewareAllowsRetry",                                                                 // Port of HttpClientTest::testExceptionThrowInMiddlewareAllowsRetry
		"HttpClientTest::testRequestsWillBeWaitingSleepMillisecondsReceivedInBackoffArray",                                          // Port of HttpClientTest::testRequestsWillBeWaitingSleepMillisecondsReceivedInBackoffArray
		"HttpClientTest::testFailedRequest",                                                                                         // Port of HttpClientTest::testFailedRequest
		"HttpClientTest::testFakeConnectionException",                                                                               // Port of HttpClientTest::testFakeConnectionException
		"HttpClientTest::testFakeConnectionExceptionWithinFakeClosure",                                                              // Port of HttpClientTest::testFakeConnectionExceptionWithinFakeClosure
		"HttpClientTest::testFakeConnectionExceptionWithinArray",                                                                    // Port of HttpClientTest::testFakeConnectionExceptionWithinArray
		"HttpClientTest::testFakeConnectionExceptionWithinSequence",                                                                 // Port of HttpClientTest::testFakeConnectionExceptionWithinSequence
		"HttpClientTest::testMiddlewareRunsWhenFaked",                                                                               // Port of HttpClientTest::testMiddlewareRunsWhenFaked
		"HttpClientTest::testMiddlewareRunsAndCanChangeRequestOnAssertSent",                                                         // Port of HttpClientTest::testMiddlewareRunsAndCanChangeRequestOnAssertSent
		"HttpClientTest::testSslCertificateErrorsConvertedToConnectionException",                                                    // Port of HttpClientTest::testSslCertificateErrorsConvertedToConnectionException
		"HttpClientTest::testConnectExceptionIsConvertedToConnectionExceptionEvenWhenWithoutFactory",                                // Port of HttpClientTest::testConnectExceptionIsConvertedToConnectionExceptionEvenWhenWithoutFactory
		"HttpClientTest::testRequestExceptionWithoutResponseIsConvertedToConnectionExceptionEvenWhenWithoutFactory",                 // Port of HttpClientTest::testRequestExceptionWithoutResponseIsConvertedToConnectionExceptionEvenWhenWithoutFactory
		"HttpClientTest::testRequestExceptionWithResponseIsConvertedToConnectionExceptionEvenWhenWithoutFactory",                    // Port of HttpClientTest::testRequestExceptionWithResponseIsConvertedToConnectionExceptionEvenWhenWithoutFactory
		"HttpClientTest::testTooManyRedirectsExceptionIsConvertedToConnectionExceptionEvenWhenWithoutFactory",                       // Port of HttpClientTest::testTooManyRedirectsExceptionIsConvertedToConnectionExceptionEvenWhenWithoutFactory
		"HttpClientTest::testTooManyRedirectsExceptionConvertedToConnectionException",                                               // Port of HttpClientTest::testTooManyRedirectsExceptionConvertedToConnectionException
		"HttpClientTest::testTooManyRedirectsWithFakedRedirectChain",                                                                // Port of HttpClientTest::testTooManyRedirectsWithFakedRedirectChain
		"HttpClientTest::testRequestExceptionIsNotThrownIfThePendingRequestIsSetToThrowOnFailureButTheResponseIsSuccessful",         // Port of HttpClientTest::testRequestExceptionIsNotThrownIfThePendingRequestIsSetToThrowOnFailureButTheResponseIsSuccessful
		"HttpClientTest::testRequestExceptionIsThrownIfThePendingRequestIsSetToThrowOnFailure",                                      // Port of HttpClientTest::testRequestExceptionIsThrownIfThePendingRequestIsSetToThrowOnFailure
		"HttpClientTest::testRequestExceptionIsThrownIfTheThrowIfOnThePendingRequestIsSetToTrueOnFailure",                           // Port of HttpClientTest::testRequestExceptionIsThrownIfTheThrowIfOnThePendingRequestIsSetToTrueOnFailure
		"HttpClientTest::testRequestExceptionIsNotThrownIfTheThrowIfOnThePendingRequestIsSetToFalseOnFailure",                       // Port of HttpClientTest::testRequestExceptionIsNotThrownIfTheThrowIfOnThePendingRequestIsSetToFalseOnFailure
		"HttpClientTest::testRequestExceptionIsThrownIfTheThrowIfClosureOnThePendingRequestReturnsTrue",                             // Port of HttpClientTest::testRequestExceptionIsThrownIfTheThrowIfClosureOnThePendingRequestReturnsTrue
		"HttpClientTest::testRequestExceptionIsNotThrownIfTheThrowIfClosureOnThePendingRequestReturnsFalse",                         // Port of HttpClientTest::testRequestExceptionIsNotThrownIfTheThrowIfClosureOnThePendingRequestReturnsFalse
		"HttpClientTest::testRequestExceptionIsThrownWithCallbackIfThePendingRequestIsSetToThrowOnFailure",                          // Port of HttpClientTest::testRequestExceptionIsThrownWithCallbackIfThePendingRequestIsSetToThrowOnFailure
		"HttpClientTest::testRequestExceptionIsThrownIfTheRequestFails",                                                             // Port of HttpClientTest::testRequestExceptionIsThrownIfTheRequestFails
		"HttpClientTest::testRequestExceptionIsThrownWithCallbackIfTheRequestFails",                                                 // Port of HttpClientTest::testRequestExceptionIsThrownWithCallbackIfTheRequestFails
		"HttpClientTest::testRequestExceptionIsNotThrownIfTheRequestDoesNotFail",                                                    // Port of HttpClientTest::testRequestExceptionIsNotThrownIfTheRequestDoesNotFail
		"HttpClientTest::testRequestExceptionIsNotReturnedIfThePendingRequestIsSetToThrowOnFailureButTheResponseIsSuccessfulInPool", // Port of HttpClientTest::testRequestExceptionIsNotReturnedIfThePendingRequestIsSetToThrowOnFailureButTheResponseIsSuccessfulInPool
		"HttpClientTest::testRequestExceptionIsReturnedIfThePendingRequestIsSetToThrowOnFailureInPool",                              // Port of HttpClientTest::testRequestExceptionIsReturnedIfThePendingRequestIsSetToThrowOnFailureInPool
		"HttpClientTest::testRequestExceptionIsReturnedIfTheThrowIfOnThePendingRequestIsSetToTrueOnFailureInPool",                   // Port of HttpClientTest::testRequestExceptionIsReturnedIfTheThrowIfOnThePendingRequestIsSetToTrueOnFailureInPool
		"HttpClientTest::testRequestExceptionIsNotReturnedIfTheThrowIfOnThePendingRequestIsSetToFalseOnFailureInPool",               // Port of HttpClientTest::testRequestExceptionIsNotReturnedIfTheThrowIfOnThePendingRequestIsSetToFalseOnFailureInPool
		"HttpClientTest::testRequestExceptionIsReturnedIfTheThrowIfClosureOnThePendingRequestReturnsTrueInPool",                     // Port of HttpClientTest::testRequestExceptionIsReturnedIfTheThrowIfClosureOnThePendingRequestReturnsTrueInPool
		"HttpClientTest::testRequestExceptionIsNotReturnedIfTheThrowIfClosureOnThePendingRequestReturnsFalseInPool",                 // Port of HttpClientTest::testRequestExceptionIsNotReturnedIfTheThrowIfClosureOnThePendingRequestReturnsFalseInPool
		"HttpClientTest::testRequestExceptionIsReturnedWithCallbackIfThePendingRequestIsSetToThrowOnFailureInPool",                  // Port of HttpClientTest::testRequestExceptionIsReturnedWithCallbackIfThePendingRequestIsSetToThrowOnFailureInPool
		"HttpClientTest::testRequestExceptionIsReturnedAfterLastRetryInPool",                                                        // Port of HttpClientTest::testRequestExceptionIsReturnedAfterLastRetryInPool
		"HttpClientTest::testRequestExceptionIsThrowIfConditionIsSatisfied",                                                         // Port of HttpClientTest::testRequestExceptionIsThrowIfConditionIsSatisfied
		"HttpClientTest::testRequestExceptionIsNotThrownIfConditionIsNotSatisfied",                                                  // Port of HttpClientTest::testRequestExceptionIsNotThrownIfConditionIsNotSatisfied
		"HttpClientTest::testRequestExceptionIsThrownWhenUnlessConditionIsNotSatisfied",                                             // Port of HttpClientTest::testRequestExceptionIsThrownWhenUnlessConditionIsNotSatisfied
		"HttpClientTest::testRequestExceptionIsNotThrownWhenUnlessConditionIsSatisfied",                                             // Port of HttpClientTest::testRequestExceptionIsNotThrownWhenUnlessConditionIsSatisfied
		"HttpClientTest::testRequestExceptionIsThrowIfConditionClosureIsSatisfied",                                                  // Port of HttpClientTest::testRequestExceptionIsThrowIfConditionClosureIsSatisfied
		"HttpClientTest::testRequestExceptionIsNotThrownIfConditionClosureIsNotSatisfied",                                           // Port of HttpClientTest::testRequestExceptionIsNotThrownIfConditionClosureIsNotSatisfied
		"HttpClientTest::testRequestExceptionIsThrownIfStatusCodeIsSatisfied",                                                       // Port of HttpClientTest::testRequestExceptionIsThrownIfStatusCodeIsSatisfied
		"HttpClientTest::testRequestExceptionIsThrownIfStatusCodeIsSatisfiedWithClosure",                                            // Port of HttpClientTest::testRequestExceptionIsThrownIfStatusCodeIsSatisfiedWithClosure
		"HttpClientTest::testRequestExceptionIsNotThrownIfStatusCodeIsNotSatisfied",                                                 // Port of HttpClientTest::testRequestExceptionIsNotThrownIfStatusCodeIsNotSatisfied
		"HttpClientTest::testRequestExceptionIsThrownUnlessStatusCodeIsSatisfied",                                                   // Port of HttpClientTest::testRequestExceptionIsThrownUnlessStatusCodeIsSatisfied
		"HttpClientTest::testRequestExceptionIsThrownIfIsClientError",                                                               // Port of HttpClientTest::testRequestExceptionIsThrownIfIsClientError
		"HttpClientTest::testThrowIfStatusWorksWithNonErrorStatusCodes",                                                             // Port of HttpClientTest::testThrowIfStatusWorksWithNonErrorStatusCodes
		"HttpClientTest::testThrowUnlessStatusWorksWithNonErrorStatusCodes",                                                         // Port of HttpClientTest::testThrowUnlessStatusWorksWithNonErrorStatusCodes
		"HttpClientTest::testRequestExceptionIsThrownIfIsServerError",                                                               // Port of HttpClientTest::testRequestExceptionIsThrownIfIsServerError
		"HttpClientTest::testItCanEnforceFaking",                                                                                    // Port of HttpClientTest::testItCanEnforceFaking
		"HttpClientTest::testItCanEnforceFakingInThePool",                                                                           // Port of HttpClientTest::testItCanEnforceFakingInThePool
		"HttpClientTest::testPreventingStrayRequests",                                                                               // Port of HttpClientTest::testPreventingStrayRequests
		"HttpClientTest::testAllowingStrayRequestUrls",                                                                              // Port of HttpClientTest::testAllowingStrayRequestUrls
		"HttpClientTest::testItCanAddAuthorizationHeaderIntoRequestUsingBeforeSendingCallback",                                      // Port of HttpClientTest::testItCanAddAuthorizationHeaderIntoRequestUsingBeforeSendingCallback
		"HttpClientTest::testItCanSetAllowMaxRedirects",                                                                             // Port of HttpClientTest::testItCanSetAllowMaxRedirects
		"HttpClientTest::testPreventDuplicatedContentType",                                                                          // Port of HttpClientTest::testPreventDuplicatedContentType
		"HttpClientTest::testItCanSubstituteUrlParams",                                                                              // Port of HttpClientTest::testItCanSubstituteUrlParams
		"HttpClientTest::testTheTransferStatsAreCustomizable",                                                                       // Port of HttpClientTest::testTheTransferStatsAreCustomizable
		"HttpClientTest::testTheTransferStatsAreCustomizableOnFake",                                                                 // Port of HttpClientTest::testTheTransferStatsAreCustomizableOnFake
		"HttpClientTest::testItCanAddGlobalMiddleware",                                                                              // Port of HttpClientTest::testItCanAddGlobalMiddleware
		"HttpClientTest::testItCanAddGlobalRequestMiddleware",                                                                       // Port of HttpClientTest::testItCanAddGlobalRequestMiddleware
		"HttpClientTest::testItCanAddGlobalResponseMiddleware",                                                                      // Port of HttpClientTest::testItCanAddGlobalResponseMiddleware
		"HttpClientTest::testItCanGetTheGlobalMiddleware",                                                                           // Port of HttpClientTest::testItCanGetTheGlobalMiddleware
		"HttpClientTest::testItCanAddRequestMiddleware",                                                                             // Port of HttpClientTest::testItCanAddRequestMiddleware
		"HttpClientTest::testItCanAddResponseMiddleware",                                                                            // Port of HttpClientTest::testItCanAddResponseMiddleware
		"HttpClientTest::testItReturnsResponse",                                                                                     // Port of HttpClientTest::testItReturnsResponse
		"HttpClientTest::testItCanReturnCustomResponseClass",                                                                        // Port of HttpClientTest::testItCanReturnCustomResponseClass
		"HttpClientTest::testItCanHaveGlobalDefaultValues",                                                                          // Port of HttpClientTest::testItCanHaveGlobalDefaultValues
		"HttpClientTest::testItCanCreatePendingRequest",                                                                             // Port of HttpClientTest::testItCanCreatePendingRequest
		"HttpClientTest::testBatchNoCallbacks",                                                                                      // Port of HttpClientTest::testBatchNoCallbacks
		"HttpClientTest::testBatchDefer",                                                                                            // Port of HttpClientTest::testBatchDefer
		"HttpClientTest::testCannotAddRequestsToInProgressBatch",                                                                    // Port of HttpClientTest::testCannotAddRequestsToInProgressBatch
		"HttpClientTest::testBatchBeforeHook",                                                                                       // Port of HttpClientTest::testBatchBeforeHook
		"HttpClientTest::testBatchProgressHook",                                                                                     // Port of HttpClientTest::testBatchProgressHook
		"HttpClientTest::testBatchCatchHook",                                                                                        // Port of HttpClientTest::testBatchCatchHook
		"HttpClientTest::testBatchThenHookIsCalled",                                                                                 // Port of HttpClientTest::testBatchThenHookIsCalled
		"HttpClientTest::testBatchThenHookIsNotCalled",                                                                              // Port of HttpClientTest::testBatchThenHookIsNotCalled
		"HttpClientTest::testBatchFinallyHookIsCalledWithoutErrors",                                                                 // Port of HttpClientTest::testBatchFinallyHookIsCalledWithoutErrors
		"HttpClientTest::testBatchFinallyHookIsCalledWithErrors",                                                                    // Port of HttpClientTest::testBatchFinallyHookIsCalledWithErrors
		"HttpClientTest::testBatchConcurrency",                                                                                      // Port of HttpClientTest::testBatchConcurrency
		"HttpClientTest::testAfterResponse",                                                                                         // Port of HttpClientTest::testAfterResponse
		"HttpClientTest::testAfterResponseWithThrows",                                                                               // Port of HttpClientTest::testAfterResponseWithThrows
		"HttpClientTest::testAfterResponseWithAsync",                                                                                // Port of HttpClientTest::testAfterResponseWithAsync
		"HttpClientTest::testRespectsDefaultFlags",                                                                                  // Port of HttpClientTest::testRespectsDefaultFlags
		"HttpClientTest::testJsonDecodingIsCachedWhenFlagsMatch",                                                                    // Port of HttpClientTest::testJsonDecodingIsCachedWhenFlagsMatch
		"HttpJsonResponseTest::testSetAndRetrieveData",                                                                              // Port of HttpJsonResponseTest::testSetAndRetrieveData
		"HttpJsonResponseTest::testGetOriginalContent",                                                                              // Port of HttpJsonResponseTest::testGetOriginalContent
		"HttpJsonResponseTest::testSetAndRetrieveOptions",                                                                           // Port of HttpJsonResponseTest::testSetAndRetrieveOptions
		"HttpJsonResponseTest::testSetAndRetrieveDefaultOptions",                                                                    // Port of HttpJsonResponseTest::testSetAndRetrieveDefaultOptions
		"HttpJsonResponseTest::testSetAndRetrieveStatusCode",                                                                        // Port of HttpJsonResponseTest::testSetAndRetrieveStatusCode
		"HttpJsonResponseTest::testInvalidArgumentExceptionOnJsonError",                                                             // Port of HttpJsonResponseTest::testInvalidArgumentExceptionOnJsonError
		"HttpJsonResponseTest::testGracefullyHandledSomeJsonErrorsWithPartialOutputOnError",                                         // Port of HttpJsonResponseTest::testGracefullyHandledSomeJsonErrorsWithPartialOutputOnError
		"HttpJsonResponseTest::testFromJsonString",                                                                                  // Port of HttpJsonResponseTest::testFromJsonString
		"HttpMimeTypeTest::testMimeTypeFromFileNameExistsTrue",                                                                      // Port of HttpMimeTypeTest::testMimeTypeFromFileNameExistsTrue
		"HttpMimeTypeTest::testMimeTypeFromFileNameExistsFalse",                                                                     // Port of HttpMimeTypeTest::testMimeTypeFromFileNameExistsFalse
		"HttpMimeTypeTest::testMimeTypeFromExtensionExistsTrue",                                                                     // Port of HttpMimeTypeTest::testMimeTypeFromExtensionExistsTrue
		"HttpMimeTypeTest::testMimeTypeFromExtensionExistsFalse",                                                                    // Port of HttpMimeTypeTest::testMimeTypeFromExtensionExistsFalse
		"HttpMimeTypeTest::testMimeTypeSymfonyInstance",                                                                             // Port of HttpMimeTypeTest::testMimeTypeSymfonyInstance
		"HttpMimeTypeTest::testSearchExtensionFromMimeType",                                                                         // Port of HttpMimeTypeTest::testSearchExtensionFromMimeType
		"HttpRedirectResponseTest::testHeaderOnRedirect",                                                                            // Port of HttpRedirectResponseTest::testHeaderOnRedirect
		"HttpRedirectResponseTest::testWithOnRedirect",                                                                              // Port of HttpRedirectResponseTest::testWithOnRedirect
		"HttpRedirectResponseTest::testWithCookieOnRedirect",                                                                        // Port of HttpRedirectResponseTest::testWithCookieOnRedirect
		"HttpRedirectResponseTest::testFragmentIdentifierOnRedirect",                                                                // Port of HttpRedirectResponseTest::testFragmentIdentifierOnRedirect
		"HttpRedirectResponseTest::testInputOnRedirect",                                                                             // Port of HttpRedirectResponseTest::testInputOnRedirect
		"HttpRedirectResponseTest::testWithCookies",                                                                                 // Port of HttpRedirectResponseTest::testWithCookies
		"HttpRedirectResponseTest::testOnlyInputOnRedirect",                                                                         // Port of HttpRedirectResponseTest::testOnlyInputOnRedirect
		"HttpRedirectResponseTest::testExceptInputOnRedirect",                                                                       // Port of HttpRedirectResponseTest::testExceptInputOnRedirect
		"HttpRedirectResponseTest::testFlashingErrorsOnRedirect",                                                                    // Port of HttpRedirectResponseTest::testFlashingErrorsOnRedirect
		"HttpRedirectResponseTest::testCanEnforceSameOriginWhenSameOrigin",                                                          // Port of HttpRedirectResponseTest::testCanEnforceSameOriginWhenSameOrigin
		"HttpRedirectResponseTest::testCanEnforceSameOriginWhenSameOriginAndCustomPort",                                             // Port of HttpRedirectResponseTest::testCanEnforceSameOriginWhenSameOriginAndCustomPort
		"HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSameScheme",                                                       // Port of HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSameScheme
		"HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSameHostname",                                                     // Port of HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSameHostname
		"HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSamePort",                                                         // Port of HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSamePort
		"HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSameSchemeAndSchemeValidationIsDisabled",                          // Port of HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSameSchemeAndSchemeValidationIsDisabled
		"HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSamePortAndPortValidationIsDisabled",                              // Port of HttpRedirectResponseTest::testCanEnforceSameOriginWhenNotSamePortAndPortValidationIsDisabled
		"HttpRedirectResponseTest::testSettersGettersOnRequest",                                                                     // Port of HttpRedirectResponseTest::testSettersGettersOnRequest
		"HttpRedirectResponseTest::testRedirectWithErrorsArrayConvertsToMessageBag",                                                 // Port of HttpRedirectResponseTest::testRedirectWithErrorsArrayConvertsToMessageBag
		"HttpRedirectResponseTest::testMagicCall",                                                                                   // Port of HttpRedirectResponseTest::testMagicCall
		"HttpRedirectResponseTest::testMagicCallException",                                                                          // Port of HttpRedirectResponseTest::testMagicCallException
		"HttpRequestTest::testInstanceMethod",                                                                                       // Port of HttpRequestTest::testInstanceMethod
		"HttpRequestTest::testMethodMethod",                                                                                         // Port of HttpRequestTest::testMethodMethod
		"HttpRequestTest::testRootMethod",                                                                                           // Port of HttpRequestTest::testRootMethod
		"HttpRequestTest::testPathMethod",                                                                                           // Port of HttpRequestTest::testPathMethod
		"HttpRequestTest::testDecodedPathMethod",                                                                                    // Port of HttpRequestTest::testDecodedPathMethod
		"HttpRequestTest::testSegmentMethod",                                                                                        // Port of HttpRequestTest::testSegmentMethod
		"HttpRequestTest::testSegmentsMethod",                                                                                       // Port of HttpRequestTest::testSegmentsMethod
		"HttpRequestTest::testUrlMethod",                                                                                            // Port of HttpRequestTest::testUrlMethod
		"HttpRequestTest::testFullUrlMethod",                                                                                        // Port of HttpRequestTest::testFullUrlMethod
		"HttpRequestTest::testFullUrlWithoutQueryMethod",                                                                            // Port of HttpRequestTest::testFullUrlWithoutQueryMethod
		"HttpRequestTest::testIsMethod",                                                                                             // Port of HttpRequestTest::testIsMethod
		"HttpRequestTest::testFullUrlIsMethod",                                                                                      // Port of HttpRequestTest::testFullUrlIsMethod
		"HttpRequestTest::testRouteIsMethod",                                                                                        // Port of HttpRequestTest::testRouteIsMethod
		"HttpRequestTest::testRouteMethod",                                                                                          // Port of HttpRequestTest::testRouteMethod
		"HttpRequestTest::testAjaxMethod",                                                                                           // Port of HttpRequestTest::testAjaxMethod
		"HttpRequestTest::testPrefetchMethod",                                                                                       // Port of HttpRequestTest::testPrefetchMethod
		"HttpRequestTest::testPjaxMethod",                                                                                           // Port of HttpRequestTest::testPjaxMethod
		"HttpRequestTest::testSecureMethod",                                                                                         // Port of HttpRequestTest::testSecureMethod
		"HttpRequestTest::testUserAgentMethod",                                                                                      // Port of HttpRequestTest::testUserAgentMethod
		"HttpRequestTest::testHostMethod",                                                                                           // Port of HttpRequestTest::testHostMethod
		"HttpRequestTest::testHttpHostMethod",                                                                                       // Port of HttpRequestTest::testHttpHostMethod
		"HttpRequestTest::testSchemeAndHttpHostMethod",                                                                              // Port of HttpRequestTest::testSchemeAndHttpHostMethod
		"HttpRequestTest::testHasMethod",                                                                                            // Port of HttpRequestTest::testHasMethod
		"HttpRequestTest::testWhenHasMethod",                                                                                        // Port of HttpRequestTest::testWhenHasMethod
		"HttpRequestTest::testWhenFilledMethod",                                                                                     // Port of HttpRequestTest::testWhenFilledMethod
		"HttpRequestTest::testMissingMethod",                                                                                        // Port of HttpRequestTest::testMissingMethod
		"HttpRequestTest::testWhenMissingMethod",                                                                                    // Port of HttpRequestTest::testWhenMissingMethod
		"HttpRequestTest::testHasAnyMethod",                                                                                         // Port of HttpRequestTest::testHasAnyMethod
		"HttpRequestTest::testFilledMethod",                                                                                         // Port of HttpRequestTest::testFilledMethod
		"HttpRequestTest::testIsNotFilledMethod",                                                                                    // Port of HttpRequestTest::testIsNotFilledMethod
		"HttpRequestTest::testFilledAnyMethod",                                                                                      // Port of HttpRequestTest::testFilledAnyMethod
		"HttpRequestTest::testInputMethod",                                                                                          // Port of HttpRequestTest::testInputMethod
		"HttpRequestTest::testFluentMethod",                                                                                         // Port of HttpRequestTest::testFluentMethod
		"HttpRequestTest::testStringMethod",                                                                                         // Port of HttpRequestTest::testStringMethod
		"HttpRequestTest::testBooleanMethod",                                                                                        // Port of HttpRequestTest::testBooleanMethod
		"HttpRequestTest::testIntegerMethod",                                                                                        // Port of HttpRequestTest::testIntegerMethod
		"HttpRequestTest::testFloatMethod",                                                                                          // Port of HttpRequestTest::testFloatMethod
		"HttpRequestTest::testArrayMethod",                                                                                          // Port of HttpRequestTest::testArrayMethod
		"HttpRequestTest::testCollectMethod",                                                                                        // Port of HttpRequestTest::testCollectMethod
		"HttpRequestTest::testDateMethod",                                                                                           // Port of HttpRequestTest::testDateMethod
		"HttpRequestTest::testDateMethodExceptionWhenValueInvalid",                                                                  // Port of HttpRequestTest::testDateMethodExceptionWhenValueInvalid
		"HttpRequestTest::testDateMethodExceptionWhenFormatInvalid",                                                                 // Port of HttpRequestTest::testDateMethodExceptionWhenFormatInvalid
		"HttpRequestTest::testIntervalMethod",                                                                                       // Port of HttpRequestTest::testIntervalMethod
		"HttpRequestTest::testIntervalMethodWithScientificNotationFloats",                                                           // Port of HttpRequestTest::testIntervalMethodWithScientificNotationFloats
		"HttpRequestTest::testEnumMethod",                                                                                           // Port of HttpRequestTest::testEnumMethod
		"HttpRequestTest::testEnumsMethod",                                                                                          // Port of HttpRequestTest::testEnumsMethod
		"HttpRequestTest::testArrayAccess",                                                                                          // Port of HttpRequestTest::testArrayAccess
		"HttpRequestTest::testArrayAccessWithoutRouteResolver",                                                                      // Port of HttpRequestTest::testArrayAccessWithoutRouteResolver
		"HttpRequestTest::testAllMethod",                                                                                            // Port of HttpRequestTest::testAllMethod
		"HttpRequestTest::testKeysMethod",                                                                                           // Port of HttpRequestTest::testKeysMethod
		"HttpRequestTest::testOnlyMethod",                                                                                           // Port of HttpRequestTest::testOnlyMethod
		"HttpRequestTest::testExceptMethod",                                                                                         // Port of HttpRequestTest::testExceptMethod
		"HttpRequestTest::testQueryMethod",                                                                                          // Port of HttpRequestTest::testQueryMethod
		"HttpRequestTest::testPostMethod",                                                                                           // Port of HttpRequestTest::testPostMethod
		"HttpRequestTest::testCookieMethod",                                                                                         // Port of HttpRequestTest::testCookieMethod
		"HttpRequestTest::testHasCookieMethod",                                                                                      // Port of HttpRequestTest::testHasCookieMethod
		"HttpRequestTest::testFileMethod",                                                                                           // Port of HttpRequestTest::testFileMethod
		"HttpRequestTest::testHasFileMethod",                                                                                        // Port of HttpRequestTest::testHasFileMethod
		"HttpRequestTest::testServerMethod",                                                                                         // Port of HttpRequestTest::testServerMethod
		"HttpRequestTest::testMergeMethod",                                                                                          // Port of HttpRequestTest::testMergeMethod
		"HttpRequestTest::testMergeIfMissingMethod",                                                                                 // Port of HttpRequestTest::testMergeIfMissingMethod
		"HttpRequestTest::testReplaceMethod",                                                                                        // Port of HttpRequestTest::testReplaceMethod
		"HttpRequestTest::testOffsetUnsetMethod",                                                                                    // Port of HttpRequestTest::testOffsetUnsetMethod
		"HttpRequestTest::testHeaderMethod",                                                                                         // Port of HttpRequestTest::testHeaderMethod
		"HttpRequestTest::testBearerTokenMethod",                                                                                    // Port of HttpRequestTest::testBearerTokenMethod
		"HttpRequestTest::testJSONMethod",                                                                                           // Port of HttpRequestTest::testJSONMethod
		"HttpRequestTest::testJSONEmulatingPHPBuiltInServer",                                                                        // Port of HttpRequestTest::testJSONEmulatingPHPBuiltInServer
		"HttpRequestTest::testPrefersMethod",                                                                                        // Port of HttpRequestTest::testPrefersMethod
		"HttpRequestTest::testAllInputReturnsInputAndFiles",                                                                         // Port of HttpRequestTest::testAllInputReturnsInputAndFiles
		"HttpRequestTest::testAllInputReturnsNestedInputAndFiles",                                                                   // Port of HttpRequestTest::testAllInputReturnsNestedInputAndFiles
		"HttpRequestTest::testAllInputReturnsInputAfterReplace",                                                                     // Port of HttpRequestTest::testAllInputReturnsInputAfterReplace
		"HttpRequestTest::testAllInputWithNumericKeysReturnsInputAfterReplace",                                                      // Port of HttpRequestTest::testAllInputWithNumericKeysReturnsInputAfterReplace
		"HttpRequestTest::testInputWithEmptyFilename",                                                                               // Port of HttpRequestTest::testInputWithEmptyFilename
		"HttpRequestTest::testMultipleFileUploadWithEmptyValue",                                                                     // Port of HttpRequestTest::testMultipleFileUploadWithEmptyValue
		"HttpRequestTest::testOldMethodCallsSession",                                                                                // Port of HttpRequestTest::testOldMethodCallsSession
		"HttpRequestTest::testOldMethodCallsSessionWhenDefaultIsArray",                                                              // Port of HttpRequestTest::testOldMethodCallsSessionWhenDefaultIsArray
		"HttpRequestTest::testOldMethodCanGetDefaultValueFromModelByKey",                                                            // Port of HttpRequestTest::testOldMethodCanGetDefaultValueFromModelByKey
		"HttpRequestTest::testFlushMethodCallsSession",                                                                              // Port of HttpRequestTest::testFlushMethodCallsSession
		"HttpRequestTest::testExpectsJson",                                                                                          // Port of HttpRequestTest::testExpectsJson
		"HttpRequestTest::testFormatReturnsAcceptableFormat",                                                                        // Port of HttpRequestTest::testFormatReturnsAcceptableFormat
		"HttpRequestTest::testWantsMarkdown",                                                                                        // Port of HttpRequestTest::testWantsMarkdown
		"HttpRequestTest::testAcceptsMarkdown",                                                                                      // Port of HttpRequestTest::testAcceptsMarkdown
		"HttpRequestTest::testFormatReturnsAcceptsJson",                                                                             // Port of HttpRequestTest::testFormatReturnsAcceptsJson
		"HttpRequestTest::testFormatReturnsAcceptsHtml",                                                                             // Port of HttpRequestTest::testFormatReturnsAcceptsHtml
		"HttpRequestTest::testFormatReturnsAcceptsAll",                                                                              // Port of HttpRequestTest::testFormatReturnsAcceptsAll
		"HttpRequestTest::testFormatReturnsAcceptsMultiple",                                                                         // Port of HttpRequestTest::testFormatReturnsAcceptsMultiple
		"HttpRequestTest::testFormatReturnsAcceptsCharset",                                                                          // Port of HttpRequestTest::testFormatReturnsAcceptsCharset
		"HttpRequestTest::testWantsJsonRespectsHeaderChanges",                                                                       // Port of HttpRequestTest::testWantsJsonRespectsHeaderChanges
		"HttpRequestTest::testAcceptsJsonRespectsHeaderChanges",                                                                     // Port of HttpRequestTest::testAcceptsJsonRespectsHeaderChanges
		"HttpRequestTest::testPrefersRespectsHeaderChanges",                                                                         // Port of HttpRequestTest::testPrefersRespectsHeaderChanges
		"HttpRequestTest::testWantsJsonWorksWhenHeaderSetBeforeFirstCall",                                                           // Port of HttpRequestTest::testWantsJsonWorksWhenHeaderSetBeforeFirstCall
		"HttpRequestTest::testCacheClearedWhenTransitioningFromUnsetToSetHeader",                                                    // Port of HttpRequestTest::testCacheClearedWhenTransitioningFromUnsetToSetHeader
		"HttpRequestTest::testAcceptsJsonWorksWhenHeaderChangedMultipleTimes",                                                       // Port of HttpRequestTest::testAcceptsJsonWorksWhenHeaderChangedMultipleTimes
		"HttpRequestTest::testBadAcceptHeader",                                                                                      // Port of HttpRequestTest::testBadAcceptHeader
		"HttpRequestTest::testCaseInsensitiveAcceptHeader",                                                                          // Port of HttpRequestTest::testCaseInsensitiveAcceptHeader
		"HttpRequestTest::testSessionMethod",                                                                                        // Port of HttpRequestTest::testSessionMethod
		"HttpRequestTest::testHasSessionMethod",                                                                                     // Port of HttpRequestTest::testHasSessionMethod
		"HttpRequestTest::testGetSessionMethodWithUpstreamSession",                                                                   // Port of HttpRequestTest::testGetSessionMethodWithUpstreamSession
		"HttpRequestTest::testGetSessionMethodWithoutUpstreamSession",                                                                // Port of HttpRequestTest::testGetSessionMethodWithoutUpstreamSession
		"HttpRequestTest::testUserResolverMakesUserAvailableAsMagicProperty",                                                        // Port of HttpRequestTest::testUserResolverMakesUserAvailableAsMagicProperty
		"HttpRequestTest::testFingerprintMethod",                                                                                    // Port of HttpRequestTest::testFingerprintMethod
		"HttpRequestTest::testFingerprintWithoutRoute",                                                                              // Port of HttpRequestTest::testFingerprintWithoutRoute
		"HttpRequestTest::testJsonRequestFillsRequestBodyParams",                                                                    // Port of HttpRequestTest::testJsonRequestFillsRequestBodyParams
		"HttpRequestTest::testNonJsonRequestDoesntFillRequestBodyParams",                                                            // Port of HttpRequestTest::testNonJsonRequestDoesntFillRequestBodyParams
		"HttpRequestTest::testMagicMethods",                                                                                         // Port of HttpRequestTest::testMagicMethods
		"HttpRequestTest::testHttpRequestFlashCallsSessionFlashInputWithInputData",                                                  // Port of HttpRequestTest::testHttpRequestFlashCallsSessionFlashInputWithInputData
		"HttpRequestTest::testHttpRequestFlashOnlyCallsFlashWithProperParameters",                                                   // Port of HttpRequestTest::testHttpRequestFlashOnlyCallsFlashWithProperParameters
		"HttpRequestTest::testHttpRequestFlashExceptCallsFlashWithProperParameters",                                                 // Port of HttpRequestTest::testHttpRequestFlashExceptCallsFlashWithProperParameters
		"HttpRequestTest::testGeneratingJsonRequestFromParentRequestUsesCorrectType",                                                // Port of HttpRequestTest::testGeneratingJsonRequestFromParentRequestUsesCorrectType
		"HttpRequestTest::testJsonRequestsCanMergeDataIntoJsonRequest",                                                              // Port of HttpRequestTest::testJsonRequestsCanMergeDataIntoJsonRequest
		"HttpRequestTest::testItCanHaveObjectsInJsonPayload",                                                                        // Port of HttpRequestTest::testItCanHaveObjectsInJsonPayload
		"HttpRequestTest::testItDoesNotGenerateJsonErrorsForEmptyContent",                                                           // Port of HttpRequestTest::testItDoesNotGenerateJsonErrorsForEmptyContent
		"HttpRequestTest::testItClampsValues",                                                                                       // Port of HttpRequestTest::testItClampsValues
		"HttpResponseTest::testJsonResponsesAreConvertedAndHeadersAreSet",                                                           // Port of HttpResponseTest::testJsonResponsesAreConvertedAndHeadersAreSet
		"HttpResponseTest::testRenderablesAreRendered",                                                                              // Port of HttpResponseTest::testRenderablesAreRendered
		"HttpResponseTest::testHeader",                                                                                              // Port of HttpResponseTest::testHeader
		"HttpResponseTest::testWithCookie",                                                                                          // Port of HttpResponseTest::testWithCookie
		"HttpResponseTest::testResponseCookiesInheritRequestSecureState",                                                            // Port of HttpResponseTest::testResponseCookiesInheritRequestSecureState
		"HttpResponseTest::testGetOriginalContent",                                                                                  // Port of HttpResponseTest::testGetOriginalContent
		"HttpResponseTest::testGetOriginalContentRetrievesTheFirstOriginalContent",                                                  // Port of HttpResponseTest::testGetOriginalContentRetrievesTheFirstOriginalContent
		"HttpResponseTest::testSetAndRetrieveStatusCode",                                                                            // Port of HttpResponseTest::testSetAndRetrieveStatusCode
		"HttpResponseTest::testSetStatusCodeAndRetrieveStatusText",                                                                  // Port of HttpResponseTest::testSetStatusCodeAndRetrieveStatusText
		"HttpResponseTest::testOnlyInputOnRedirect",                                                                                 // Port of HttpResponseTest::testOnlyInputOnRedirect
		"HttpResponseTest::testExceptInputOnRedirect",                                                                               // Port of HttpResponseTest::testExceptInputOnRedirect
		"HttpResponseTest::testFlashingErrorsOnRedirect",                                                                            // Port of HttpResponseTest::testFlashingErrorsOnRedirect
		"HttpResponseTest::testSettersGettersOnRequest",                                                                             // Port of HttpResponseTest::testSettersGettersOnRequest
		"HttpResponseTest::testRedirectWithErrorsArrayConvertsToMessageBag",                                                         // Port of HttpResponseTest::testRedirectWithErrorsArrayConvertsToMessageBag
		"HttpResponseTest::testWithHeaders",                                                                                         // Port of HttpResponseTest::testWithHeaders
		"HttpResponseTest::testWithoutHeader",                                                                                       // Port of HttpResponseTest::testWithoutHeader
		"HttpResponseTest::testMagicCall",                                                                                           // Port of HttpResponseTest::testMagicCall
		"HttpResponseTest::testMagicCallException",                                                                                  // Port of HttpResponseTest::testMagicCallException
		"HttpTestingFileFactoryTest::testImagePng",                                                                                  // Port of HttpTestingFileFactoryTest::testImagePng
		"HttpTestingFileFactoryTest::testImageJpeg",                                                                                 // Port of HttpTestingFileFactoryTest::testImageJpeg
		"HttpTestingFileFactoryTest::testImageGif",                                                                                  // Port of HttpTestingFileFactoryTest::testImageGif
		"HttpTestingFileFactoryTest::testImageWebp",                                                                                 // Port of HttpTestingFileFactoryTest::testImageWebp
		"HttpTestingFileFactoryTest::testImageWbmp",                                                                                 // Port of HttpTestingFileFactoryTest::testImageWbmp
		"HttpTestingFileFactoryTest::testImageBmp",                                                                                  // Port of HttpTestingFileFactoryTest::testImageBmp
		"HttpTestingFileFactoryTest::testCreateWithMimeType",                                                                        // Port of HttpTestingFileFactoryTest::testCreateWithMimeType
		"HttpTestingFileFactoryTest::testCreateWithoutMimeType",                                                                     // Port of HttpTestingFileFactoryTest::testCreateWithoutMimeType
		"HttpTestingFileFactoryTest::testCallingCreateWithoutGDLoadedThrowsAnException",                                             // Port of HttpTestingFileFactoryTest::testCallingCreateWithoutGDLoadedThrowsAnException
		"HttpUploadedFileTest::testUploadedFileCanRetrieveContentsFromTextFile",                                                     // Port of HttpUploadedFileTest::testUploadedFileCanRetrieveContentsFromTextFile
		"HttpUploadedFileTest::testUploadedFileInRequestContainsOriginalPathAndName",                                                // Port of HttpUploadedFileTest::testUploadedFileInRequestContainsOriginalPathAndName
		"JsonResourceTest::testJsonResourceNullAttributes",                                                                          // Port of JsonResourceTest::testJsonResourceNullAttributes
		"JsonResourceTest::testJsonResourceToJsonSucceedsWithPriorErrors",                                                           // Port of JsonResourceTest::testJsonResourceToJsonSucceedsWithPriorErrors
		"JsonResourceTest::testJsonResourceToPrettyPrint",                                                                           // Port of JsonResourceTest::testJsonResourceToPrettyPrint
		"CacheTest::testItCanGenerateDefinitionViaStaticMethod",                                                                     // Port of CacheTest::testItCanGenerateDefinitionViaStaticMethod
		"CacheTest::testDoNotSetHeaderWhenMethodNotCacheable",                                                                       // Port of CacheTest::testDoNotSetHeaderWhenMethodNotCacheable
		"CacheTest::testDoNotSetHeaderWhenNoContent",                                                                                // Port of CacheTest::testDoNotSetHeaderWhenNoContent
		"CacheTest::testSetHeaderToFileResponseEvenWithNoContent",                                                                   // Port of CacheTest::testSetHeaderToFileResponseEvenWithNoContent
		"CacheTest::testSetHeaderToDownloadResponseEvenWithNoContent",                                                               // Port of CacheTest::testSetHeaderToDownloadResponseEvenWithNoContent
		"CacheTest::testAddHeaders",                                                                                                 // Port of CacheTest::testAddHeaders
		"CacheTest::testAddHeadersUsingArray",                                                                                       // Port of CacheTest::testAddHeadersUsingArray
		"CacheTest::testGenerateEtag",                                                                                               // Port of CacheTest::testGenerateEtag
		"CacheTest::testDoesNotOverrideEtag",                                                                                        // Port of CacheTest::testDoesNotOverrideEtag
		"CacheTest::testIsNotModified",                                                                                              // Port of CacheTest::testIsNotModified
		"CacheTest::testInvalidOption",                                                                                              // Port of CacheTest::testInvalidOption
		"CacheTest::testLastModifiedUnixTime",                                                                                       // Port of CacheTest::testLastModifiedUnixTime
		"CacheTest::testLastModifiedStringDate",                                                                                     // Port of CacheTest::testLastModifiedStringDate
		"CacheTest::testTrailingDelimiterIgnored",                                                                                   // Port of CacheTest::testTrailingDelimiterIgnored
		"CacheTest::testItDoesNotSetEtagHeadersForBinaryContent",                                                                    // Port of CacheTest::testItDoesNotSetEtagHeadersForBinaryContent
		"PrefersJsonResponsesTest::testItRewritesMissingAcceptHeader",                                                               // Port of PrefersJsonResponsesTest::testItRewritesMissingAcceptHeader
		"PrefersJsonResponsesTest::testItRewritesEmptyAcceptHeader",                                                                 // Port of PrefersJsonResponsesTest::testItRewritesEmptyAcceptHeader
		"PrefersJsonResponsesTest::testItRewritesStarSlashStarAcceptHeader",                                                         // Port of PrefersJsonResponsesTest::testItRewritesStarSlashStarAcceptHeader
		"PrefersJsonResponsesTest::testItDoesNotRewriteBareStarAcceptHeader",                                                        // Port of PrefersJsonResponsesTest::testItDoesNotRewriteBareStarAcceptHeader
		"PrefersJsonResponsesTest::testItRewritesApplicationWildcardAcceptHeader",                                                   // Port of PrefersJsonResponsesTest::testItRewritesApplicationWildcardAcceptHeader
		"PrefersJsonResponsesTest::testItRewritesBroadAcceptHeaderWithQualityParameter",                                             // Port of PrefersJsonResponsesTest::testItRewritesBroadAcceptHeaderWithQualityParameter
		"PrefersJsonResponsesTest::testItRewritesMultipleBroadMarkers",                                                              // Port of PrefersJsonResponsesTest::testItRewritesMultipleBroadMarkers
		"PrefersJsonResponsesTest::testItInvokesNextAndReturnsItsResponse",                                                          // Port of PrefersJsonResponsesTest::testItInvokesNextAndReturnsItsResponse
		"PrefersJsonResponsesTest::testItLeavesExplicitHtmlAcceptHeader",                                                            // Port of PrefersJsonResponsesTest::testItLeavesExplicitHtmlAcceptHeader
		"PrefersJsonResponsesTest::testItLeavesExplicitXmlAcceptHeader",                                                             // Port of PrefersJsonResponsesTest::testItLeavesExplicitXmlAcceptHeader
		"PrefersJsonResponsesTest::testItLeavesExplicitPlainTextAcceptHeader",                                                       // Port of PrefersJsonResponsesTest::testItLeavesExplicitPlainTextAcceptHeader
		"PrefersJsonResponsesTest::testItLeavesMultiValueExplicitAcceptList",                                                        // Port of PrefersJsonResponsesTest::testItLeavesMultiValueExplicitAcceptList
		"PrefersJsonResponsesTest::testItLeavesMixedBroadAndExplicitAcceptList",                                                     // Port of PrefersJsonResponsesTest::testItLeavesMixedBroadAndExplicitAcceptList
		"PrefersJsonResponsesTest::testItLeavesWildcardFirstMixedAcceptList",                                                        // Port of PrefersJsonResponsesTest::testItLeavesWildcardFirstMixedAcceptList
		"PrefersJsonResponsesTest::testItLeavesExplicitJsonAcceptHeader",                                                            // Port of PrefersJsonResponsesTest::testItLeavesExplicitJsonAcceptHeader
		"PrefersJsonResponsesTest::testItDoesNotMutateBodyMethodUriQueryOrOtherHeaders",                                             // Port of PrefersJsonResponsesTest::testItDoesNotMutateBodyMethodUriQueryOrOtherHeaders
		"PreventRequestForgeryTest::test_same_origin_header_passes",                                                                 // Port of PreventRequestForgeryTest::test_same_origin_header_passes
		"PreventRequestForgeryTest::test_same_site_header_rejected_by_default",                                                      // Port of PreventRequestForgeryTest::test_same_site_header_rejected_by_default
		"PreventRequestForgeryTest::test_same_site_header_passes_when_allowed",                                                      // Port of PreventRequestForgeryTest::test_same_site_header_passes_when_allowed
		"PreventRequestForgeryTest::test_cross_site_with_valid_token_passes",                                                        // Port of PreventRequestForgeryTest::test_cross_site_with_valid_token_passes
		"PreventRequestForgeryTest::test_cross_site_without_token_fails",                                                            // Port of PreventRequestForgeryTest::test_cross_site_without_token_fails
		"PreventRequestForgeryTest::test_missing_header_without_token_fails",                                                        // Port of PreventRequestForgeryTest::test_missing_header_without_token_fails
		"PreventRequestForgeryTest::test_origin_only_mode_rejects_cross_site",                                                       // Port of PreventRequestForgeryTest::test_origin_only_mode_rejects_cross_site
		"PreventRequestForgeryTest::test_origin_only_mode_rejects_missing_header",                                                   // Port of PreventRequestForgeryTest::test_origin_only_mode_rejects_missing_header
		"PreventRequestForgeryTest::test_origin_only_mode_passes_same_origin",                                                       // Port of PreventRequestForgeryTest::test_origin_only_mode_passes_same_origin
		"TrimStringsTest::test_no_zero_width_space_character_returns_the_same_string",                                               // Port of TrimStringsTest::test_no_zero_width_space_character_returns_the_same_string
		"TrimStringsTest::test_leading_zero_width_space_character_is_trimmed",                                                       // Port of TrimStringsTest::test_leading_zero_width_space_character_is_trimmed
		"TrimStringsTest::test_trim_strings_can_globally_ignore_certain_inputs",                                                     // Port of TrimStringsTest::test_trim_strings_can_globally_ignore_certain_inputs
		"TrimStringsTest::test_trailing_zero_width_space_character_is_trimmed",                                                      // Port of TrimStringsTest::test_trailing_zero_width_space_character_is_trimmed
		"TrimStringsTest::test_leading_zero_width_non_breakable_space_character_is_trimmed",                                         // Port of TrimStringsTest::test_leading_zero_width_non_breakable_space_character_is_trimmed
		"TrimStringsTest::test_leading_multiple_zero_width_non_breakable_space_characters_are_trimmed",                              // Port of TrimStringsTest::test_leading_multiple_zero_width_non_breakable_space_characters_are_trimmed
		"TrimStringsTest::test_combination_of_leading_and_trailing_zero_width_non_breakable_space_and_zero_width_space_characters_are_trimmed", // Port of TrimStringsTest::test_combination_of_leading_and_trailing_zero_width_non_breakable_space_and_zero_width_space_characters_are_trimmed
		"TrimStringsTest::test_leading_invisible_characters_are_trimmed",                                                                       // Port of TrimStringsTest::test_leading_invisible_characters_are_trimmed
		"TrimStringsTest::test_trailing_invisible_characters_are_trimmed",                                                                      // Port of TrimStringsTest::test_trailing_invisible_characters_are_trimmed
		"TrimStringsTest::test_leading_multiple_invisible_characters_are_trimmed",                                                              // Port of TrimStringsTest::test_leading_multiple_invisible_characters_are_trimmed
		"TrimStringsTest::test_trailing_multiple_invisible_characters_are_trimmed",                                                             // Port of TrimStringsTest::test_trailing_multiple_invisible_characters_are_trimmed
		"TrimStringsTest::test_combination_of_leading_and_trailing_multiple_invisible_characters_are_trimmed",                                  // Port of TrimStringsTest::test_combination_of_leading_and_trailing_multiple_invisible_characters_are_trimmed
		"TrimStringsTest::test_trim_strings_can_ignore_nested_attributes_using_wildcards",                                                      // Port of TrimStringsTest::test_trim_strings_can_ignore_nested_attributes_using_wildcards
		"TrustProxiesTest::test_request_does_not_trust",                                                                                        // Port of TrustProxiesTest::test_request_does_not_trust
		"TrustProxiesTest::test_does_trust_trusted_proxy",                                                                                      // Port of TrustProxiesTest::test_does_trust_trusted_proxy
		"TrustProxiesTest::test_trusted_proxy_sets_trusted_proxies_with_wildcard",                                                              // Port of TrustProxiesTest::test_trusted_proxy_sets_trusted_proxies_with_wildcard
		"TrustProxiesTest::test_trusted_proxy_sets_trusted_proxies_with_double_wildcard_for_backwards_compat",                                  // Port of TrustProxiesTest::test_trusted_proxy_sets_trusted_proxies_with_double_wildcard_for_backwards_compat
		"TrustProxiesTest::test_trusted_proxy_sets_trusted_proxies_with_REMOTE_ADDR",                                                           // Port of TrustProxiesTest::test_trusted_proxy_sets_trusted_proxies_with_REMOTE_ADDR
		"TrustProxiesTest::test_trusted_proxy_sets_trusted_proxies",                                                                            // Port of TrustProxiesTest::test_trusted_proxy_sets_trusted_proxies
		"TrustProxiesTest::test_get_client_ips",                                                                                                // Port of TrustProxiesTest::test_get_client_ips
		"TrustProxiesTest::test_get_client_ip_with_multiple_ip_addresses_some_of_which_are_trusted",                                            // Port of TrustProxiesTest::test_get_client_ip_with_multiple_ip_addresses_some_of_which_are_trusted
		"TrustProxiesTest::test_get_client_ip_with_multiple_ip_addresses_all_proxies_are_trusted",                                              // Port of TrustProxiesTest::test_get_client_ip_with_multiple_ip_addresses_all_proxies_are_trusted
		"TrustProxiesTest::test_can_distrust_headers",                                                                                          // Port of TrustProxiesTest::test_can_distrust_headers
		"TrustProxiesTest::test_x_forwarded_for_header_only_trusted",                                                                           // Port of TrustProxiesTest::test_x_forwarded_for_header_only_trusted
		"TrustProxiesTest::test_x_forwarded_host_header_only_trusted",                                                                          // Port of TrustProxiesTest::test_x_forwarded_host_header_only_trusted
		"TrustProxiesTest::test_x_forwarded_port_header_only_trusted",                                                                          // Port of TrustProxiesTest::test_x_forwarded_port_header_only_trusted
		"TrustProxiesTest::test_x_forwarded_prefix_header_only_trusted",                                                                        // Port of TrustProxiesTest::test_x_forwarded_prefix_header_only_trusted
		"TrustProxiesTest::test_x_forwarded_proto_header_only_trusted",                                                                         // Port of TrustProxiesTest::test_x_forwarded_proto_header_only_trusted
		"TrustProxiesTest::test_x_forwarded_multiple_individual_headers_trusted",                                                               // Port of TrustProxiesTest::test_x_forwarded_multiple_individual_headers_trusted
		"TrustProxiesTest::test_is_reading_text_based_configurations",                                                                          // Port of TrustProxiesTest::test_is_reading_text_based_configurations
		"VitePreloadingTest::testItDoesNotSetLinkTagWhenNoTagsHaveBeenPreloaded",                                                               // Port of VitePreloadingTest::testItDoesNotSetLinkTagWhenNoTagsHaveBeenPreloaded
		"VitePreloadingTest::testItAddsPreloadLinkHeader",                                                                                      // Port of VitePreloadingTest::testItAddsPreloadLinkHeader
		"VitePreloadingTest::testItDoesNotAttachHeadersToNonFrameworkResponses",                                                               // Port of VitePreloadingTest::testItDoesNotAttachHeadersToNonFrameworkResponses
		"VitePreloadingTest::testItDoesNotOverwriteOtherLinkHeaders",                                                                           // Port of VitePreloadingTest::testItDoesNotOverwriteOtherLinkHeaders
		"VitePreloadingTest::testItCanLimitNumberOfAssetsPreloaded",                                                                            // Port of VitePreloadingTest::testItCanLimitNumberOfAssetsPreloaded
		"VitePreloadingTest::test_it_can_configure_the_middleware",                                                                             // Port of VitePreloadingTest::test_it_can_configure_the_middleware
		"JsonApiResourceTest::testResponseWrapperIsHardCodedToData",                                                                            // Port of JsonApiResourceTest::testResponseWrapperIsHardCodedToData
		"JsonApiResourceTest::testUnableToSetWrapper",                                                                                          // Port of JsonApiResourceTest::testUnableToSetWrapper
		"JsonApiResourceTest::testUnableToUnsetWrapper",                                                                                        // Port of JsonApiResourceTest::testUnableToUnsetWrapper
		"JsonApiResourceTest::testFlushStateResetsMaxRelationshipDepthToDefault",                                                               // Port of JsonApiResourceTest::testFlushStateResetsMaxRelationshipDepthToDefault
	}

	if len(ported) != 488 {
		t.Fatalf("expected 488 Upstream inventory entries, got %d", len(ported))
	}
}
