package hashing

import (
	"fmt"

	configpkg "github.com/gollin/packages/config"
	securitypkg "github.com/gollin/packages/security"
)

// Manager dispatches hashing operations to configured drivers.
type Manager struct {
	defaultDriver string
	bcrypt        *Bcrypt
	argon         *Argon2i
	argon2id      *Argon2id
}

// NewManager creates a hashing manager from explicit config.
func NewManager(cfg Config) (*Manager, error) {
	cfg = normalizeConfig(cfg)

	manager := &Manager{
		defaultDriver: cfg.Driver,
		bcrypt:        NewBcrypt(cfg.Bcrypt),
		argon:         NewArgon2i(cfg.Argon),
		argon2id:      NewArgon2id(cfg.Argon),
	}

	if _, err := manager.Driver(cfg.Driver); err != nil {
		return nil, err
	}

	return manager, nil
}

// NewManagerFromRepository creates a hashing manager from the shared config repository.
func NewManagerFromRepository(repo *configpkg.Repository) (*Manager, error) {
	cfg, err := securitypkg.ConfigFromRepository(repo)
	if err != nil {
		return nil, err
	}

	return NewManager(cfg.Hashing)
}

// DefaultDriver returns the default driver name.
func (m *Manager) DefaultDriver() string {
	return m.defaultDriver
}

// Driver returns a named hasher.
func (m *Manager) Driver(name string) (Hasher, error) {
	switch normalizeDriver(name) {
	case DriverBcrypt:
		return m.bcrypt, nil
	case DriverArgon:
		return m.argon, nil
	case DriverArgon2id:
		return m.argon2id, nil
	default:
		return nil, fmt.Errorf("hashing: unsupported driver %q", name)
	}
}

// Info returns metadata about a hashed value.
func (m *Manager) Info(hashedValue string) Info {
	return parseInfo(hashedValue)
}

// Make hashes a plaintext value using the default driver.
func (m *Manager) Make(value string, options map[string]any) (string, error) {
	driver, err := m.Driver(m.defaultDriver)
	if err != nil {
		return "", err
	}
	return driver.Make(value, options)
}

// Check verifies a plaintext value using the default driver.
func (m *Manager) Check(value string, hashedValue string, options map[string]any) (bool, error) {
	driver, err := m.Driver(m.defaultDriver)
	if err != nil {
		return false, err
	}
	return driver.Check(value, hashedValue, options)
}

// NeedsRehash reports whether the hash should be regenerated by the default driver.
func (m *Manager) NeedsRehash(hashedValue string, options map[string]any) bool {
	driver, err := m.Driver(m.defaultDriver)
	if err != nil {
		return true
	}
	return driver.NeedsRehash(hashedValue, options)
}

// IsHashed reports whether the supplied string looks like a supported hash.
func (m *Manager) IsHashed(value string) bool {
	return m.Info(value).Algorithm != ""
}

// VerifyConfiguration verifies driver-specific configuration constraints.
func (m *Manager) VerifyConfiguration(hashedValue string) bool {
	driver, err := m.Driver(m.defaultDriver)
	if err != nil {
		return false
	}

	verifier, ok := driver.(configurationVerifier)
	if !ok {
		return true
	}
	return verifier.VerifyConfiguration(hashedValue)
}
