package money

import (
	"testing"

	"github.com/gollin/packages/support/money/currency"
	testutil "github.com/gollin/packages/support/money/tests"
)

func TestFactoryHelpers(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		fn   func(int64) *Money
		code string
	}{
		{name: "aed", fn: FromAED, code: currency.AED},
		{name: "afn", fn: FromAFN, code: currency.AFN},
		{name: "all", fn: FromALL, code: currency.ALL},
		{name: "amd", fn: FromAMD, code: currency.AMD},
		{name: "ang", fn: FromANG, code: currency.ANG},
		{name: "aoa", fn: FromAOA, code: currency.AOA},
		{name: "ars", fn: FromARS, code: currency.ARS},
		{name: "aud", fn: FromAUD, code: currency.AUD},
		{name: "awg", fn: FromAWG, code: currency.AWG},
		{name: "azn", fn: FromAZN, code: currency.AZN},
		{name: "bam", fn: FromBAM, code: currency.BAM},
		{name: "bbd", fn: FromBBD, code: currency.BBD},
		{name: "bdt", fn: FromBDT, code: currency.BDT},
		{name: "bgn", fn: FromBGN, code: currency.BGN},
		{name: "bhd", fn: FromBHD, code: currency.BHD},
		{name: "bif", fn: FromBIF, code: currency.BIF},
		{name: "bmd", fn: FromBMD, code: currency.BMD},
		{name: "bnd", fn: FromBND, code: currency.BND},
		{name: "bob", fn: FromBOB, code: currency.BOB},
		{name: "bov", fn: FromBOV, code: currency.BOV},
		{name: "brl", fn: FromBRL, code: currency.BRL},
		{name: "bsd", fn: FromBSD, code: currency.BSD},
		{name: "btn", fn: FromBTN, code: currency.BTN},
		{name: "bwp", fn: FromBWP, code: currency.BWP},
		{name: "byn", fn: FromBYN, code: currency.BYN},
		{name: "bzd", fn: FromBZD, code: currency.BZD},
		{name: "cad", fn: FromCAD, code: currency.CAD},
		{name: "cdf", fn: FromCDF, code: currency.CDF},
		{name: "che", fn: FromCHE, code: currency.CHE},
		{name: "chf", fn: FromCHF, code: currency.CHF},
		{name: "chw", fn: FromCHW, code: currency.CHW},
		{name: "clf", fn: FromCLF, code: currency.CLF},
		{name: "clp", fn: FromCLP, code: currency.CLP},
		{name: "cny", fn: FromCNY, code: currency.CNY},
		{name: "cop", fn: FromCOP, code: currency.COP},
		{name: "cou", fn: FromCOU, code: currency.COU},
		{name: "crc", fn: FromCRC, code: currency.CRC},
		{name: "cuc", fn: FromCUC, code: currency.CUC},
		{name: "cup", fn: FromCUP, code: currency.CUP},
		{name: "cve", fn: FromCVE, code: currency.CVE},
		{name: "czk", fn: FromCZK, code: currency.CZK},
		{name: "djf", fn: FromDJF, code: currency.DJF},
		{name: "dkk", fn: FromDKK, code: currency.DKK},
		{name: "dop", fn: FromDOP, code: currency.DOP},
		{name: "dzd", fn: FromDZD, code: currency.DZD},
		{name: "egp", fn: FromEGP, code: currency.EGP},
		{name: "ern", fn: FromERN, code: currency.ERN},
		{name: "etb", fn: FromETB, code: currency.ETB},
		{name: "eur", fn: FromEUR, code: currency.EUR},
		{name: "fjd", fn: FromFJD, code: currency.FJD},
		{name: "fkp", fn: FromFKP, code: currency.FKP},
		{name: "gbp", fn: FromGBP, code: currency.GBP},
		{name: "gel", fn: FromGEL, code: currency.GEL},
		{name: "ghs", fn: FromGHS, code: currency.GHS},
		{name: "gip", fn: FromGIP, code: currency.GIP},
		{name: "gmd", fn: FromGMD, code: currency.GMD},
		{name: "gnf", fn: FromGNF, code: currency.GNF},
		{name: "gtq", fn: FromGTQ, code: currency.GTQ},
		{name: "gyd", fn: FromGYD, code: currency.GYD},
		{name: "hkd", fn: FromHKD, code: currency.HKD},
		{name: "hnl", fn: FromHNL, code: currency.HNL},
		{name: "htg", fn: FromHTG, code: currency.HTG},
		{name: "huf", fn: FromHUF, code: currency.HUF},
		{name: "idr", fn: FromIDR, code: currency.IDR},
		{name: "ils", fn: FromILS, code: currency.ILS},
		{name: "inr", fn: FromINR, code: currency.INR},
		{name: "iqd", fn: FromIQD, code: currency.IQD},
		{name: "irr", fn: FromIRR, code: currency.IRR},
		{name: "isk", fn: FromISK, code: currency.ISK},
		{name: "jmd", fn: FromJMD, code: currency.JMD},
		{name: "jod", fn: FromJOD, code: currency.JOD},
		{name: "jpy", fn: FromJPY, code: currency.JPY},
		{name: "kes", fn: FromKES, code: currency.KES},
		{name: "kgs", fn: FromKGS, code: currency.KGS},
		{name: "khr", fn: FromKHR, code: currency.KHR},
		{name: "kmf", fn: FromKMF, code: currency.KMF},
		{name: "kpw", fn: FromKPW, code: currency.KPW},
		{name: "krw", fn: FromKRW, code: currency.KRW},
		{name: "kwd", fn: FromKWD, code: currency.KWD},
		{name: "kyd", fn: FromKYD, code: currency.KYD},
		{name: "kzt", fn: FromKZT, code: currency.KZT},
		{name: "lak", fn: FromLAK, code: currency.LAK},
		{name: "lbp", fn: FromLBP, code: currency.LBP},
		{name: "lkr", fn: FromLKR, code: currency.LKR},
		{name: "lrd", fn: FromLRD, code: currency.LRD},
		{name: "lsl", fn: FromLSL, code: currency.LSL},
		{name: "lyd", fn: FromLYD, code: currency.LYD},
		{name: "mad", fn: FromMAD, code: currency.MAD},
		{name: "mdl", fn: FromMDL, code: currency.MDL},
		{name: "mga", fn: FromMGA, code: currency.MGA},
		{name: "mkd", fn: FromMKD, code: currency.MKD},
		{name: "mmk", fn: FromMMK, code: currency.MMK},
		{name: "mnt", fn: FromMNT, code: currency.MNT},
		{name: "mop", fn: FromMOP, code: currency.MOP},
		{name: "mru", fn: FromMRU, code: currency.MRU},
		{name: "mur", fn: FromMUR, code: currency.MUR},
		{name: "mvr", fn: FromMVR, code: currency.MVR},
		{name: "mwk", fn: FromMWK, code: currency.MWK},
		{name: "mxn", fn: FromMXN, code: currency.MXN},
		{name: "mxv", fn: FromMXV, code: currency.MXV},
		{name: "myr", fn: FromMYR, code: currency.MYR},
		{name: "mzn", fn: FromMZN, code: currency.MZN},
		{name: "nad", fn: FromNAD, code: currency.NAD},
		{name: "ngn", fn: FromNGN, code: currency.NGN},
		{name: "nio", fn: FromNIO, code: currency.NIO},
		{name: "nok", fn: FromNOK, code: currency.NOK},
		{name: "npr", fn: FromNPR, code: currency.NPR},
		{name: "nzd", fn: FromNZD, code: currency.NZD},
		{name: "omr", fn: FromOMR, code: currency.OMR},
		{name: "pab", fn: FromPAB, code: currency.PAB},
		{name: "pen", fn: FromPEN, code: currency.PEN},
		{name: "pgk", fn: FromPGK, code: currency.PGK},
		{name: "php", fn: FromPHP, code: currency.PHP},
		{name: "pkr", fn: FromPKR, code: currency.PKR},
		{name: "pln", fn: FromPLN, code: currency.PLN},
		{name: "pyg", fn: FromPYG, code: currency.PYG},
		{name: "qar", fn: FromQAR, code: currency.QAR},
		{name: "ron", fn: FromRON, code: currency.RON},
		{name: "rsd", fn: FromRSD, code: currency.RSD},
		{name: "rub", fn: FromRUB, code: currency.RUB},
		{name: "rwf", fn: FromRWF, code: currency.RWF},
		{name: "sar", fn: FromSAR, code: currency.SAR},
		{name: "sbd", fn: FromSBD, code: currency.SBD},
		{name: "scr", fn: FromSCR, code: currency.SCR},
		{name: "sdg", fn: FromSDG, code: currency.SDG},
		{name: "sek", fn: FromSEK, code: currency.SEK},
		{name: "sgd", fn: FromSGD, code: currency.SGD},
		{name: "shp", fn: FromSHP, code: currency.SHP},
		{name: "sle", fn: FromSLE, code: currency.SLE},
		{name: "sll", fn: FromSLL, code: currency.SLL},
		{name: "sos", fn: FromSOS, code: currency.SOS},
		{name: "srd", fn: FromSRD, code: currency.SRD},
		{name: "ssp", fn: FromSSP, code: currency.SSP},
		{name: "stn", fn: FromSTN, code: currency.STN},
		{name: "svc", fn: FromSVC, code: currency.SVC},
		{name: "syp", fn: FromSYP, code: currency.SYP},
		{name: "szl", fn: FromSZL, code: currency.SZL},
		{name: "thb", fn: FromTHB, code: currency.THB},
		{name: "tjs", fn: FromTJS, code: currency.TJS},
		{name: "tmt", fn: FromTMT, code: currency.TMT},
		{name: "tnd", fn: FromTND, code: currency.TND},
		{name: "top", fn: FromTOP, code: currency.TOP},
		{name: "try", fn: FromTRY, code: currency.TRY},
		{name: "ttd", fn: FromTTD, code: currency.TTD},
		{name: "twd", fn: FromTWD, code: currency.TWD},
		{name: "tzs", fn: FromTZS, code: currency.TZS},
		{name: "uah", fn: FromUAH, code: currency.UAH},
		{name: "ugx", fn: FromUGX, code: currency.UGX},
		{name: "usd", fn: FromUSD, code: currency.USD},
		{name: "usn", fn: FromUSN, code: currency.USN},
		{name: "uyi", fn: FromUYI, code: currency.UYI},
		{name: "uyu", fn: FromUYU, code: currency.UYU},
		{name: "uyw", fn: FromUYW, code: currency.UYW},
		{name: "uzs", fn: FromUZS, code: currency.UZS},
		{name: "ves", fn: FromVES, code: currency.VES},
		{name: "vnd", fn: FromVND, code: currency.VND},
		{name: "vuv", fn: FromVUV, code: currency.VUV},
		{name: "wst", fn: FromWST, code: currency.WST},
		{name: "xaf", fn: FromXAF, code: currency.XAF},
		{name: "xag", fn: FromXAG, code: currency.XAG},
		{name: "xau", fn: FromXAU, code: currency.XAU},
		{name: "xba", fn: FromXBA, code: currency.XBA},
		{name: "xbb", fn: FromXBB, code: currency.XBB},
		{name: "xbc", fn: FromXBC, code: currency.XBC},
		{name: "xbd", fn: FromXBD, code: currency.XBD},
		{name: "xcd", fn: FromXCD, code: currency.XCD},
		{name: "xdr", fn: FromXDR, code: currency.XDR},
		{name: "xof", fn: FromXOF, code: currency.XOF},
		{name: "xpd", fn: FromXPD, code: currency.XPD},
		{name: "xpf", fn: FromXPF, code: currency.XPF},
		{name: "xpt", fn: FromXPT, code: currency.XPT},
		{name: "xsu", fn: FromXSU, code: currency.XSU},
		{name: "xts", fn: FromXTS, code: currency.XTS},
		{name: "xua", fn: FromXUA, code: currency.XUA},
		{name: "xxx", fn: FromXXX, code: currency.XXX},
		{name: "yer", fn: FromYER, code: currency.YER},
		{name: "zar", fn: FromZAR, code: currency.ZAR},
		{name: "zmw", fn: FromZMW, code: currency.ZMW},
		{name: "zwl", fn: FromZWL, code: currency.ZWL},
	}

	for _, tt := range cases {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			m := tt.fn(42)
			amount := testutil.TestRequire(t, m.Amount)

			if amount != 42 {
				t.Fatalf("%s amount = %d, want 42", tt.name, amount)
			}

			currency := testutil.TestRequire(t, m.Currency)

			if currency.Code != tt.code {
				t.Fatalf("%s currency = %s, want %s", tt.name, currency.Code, tt.code)
			}
		})
	}
}
