package mailx_test

import "testing"

func TestFrameworkMailUpstreamInventoryCoverage(t *testing.T) {
	ported := []string{
		"AttachableTest::testItCanHaveMacroConstructors",                                                       // Port of AttachableTest::testItCanHaveMacroConstructors
		"AttachableTest::testItCanUtiliseExistingApisOnNonMailBasedResourcesWithPath",                          // Port of AttachableTest::testItCanUtiliseExistingApisOnNonMailBasedResourcesWithPath
		"AttachableTest::testItCanUtiliseExistingApisOnNonMailBasedResourcesWithArgs",                          // Port of AttachableTest::testItCanUtiliseExistingApisOnNonMailBasedResourcesWithArgs
		"AttachableTest::testFromUrlMethod",                                                                    // Port of AttachableTest::testFromUrlMethod
		"AttachableTest::testFromUploadedFileMethod",                                                           // Port of AttachableTest::testFromUploadedFileMethod
		"MailCloudflareTransportTest::testGetTransport",                                                        // Port of MailCloudflareTransportTest::testGetTransport
		"MailCloudflareTransportTest::testSend",                                                                // Port of MailCloudflareTransportTest::testSend
		"MailCloudflareTransportTest::testSendWithNamedAddresses",                                              // Port of MailCloudflareTransportTest::testSendWithNamedAddresses
		"MailCloudflareTransportTest::testSendWithAttachment",                                                  // Port of MailCloudflareTransportTest::testSendWithAttachment
		"MailCloudflareTransportTest::testSendThrowsOnApiFailure",                                              // Port of MailCloudflareTransportTest::testSendThrowsOnApiFailure
		"MailFailoverTransportTest::testGetFailoverTransportWithConfiguredTransports",                          // Port of MailFailoverTransportTest::testGetFailoverTransportWithConfiguredTransports
		"MailFailoverTransportTest::testGetFailoverTransportWithUpstream6StyleMailConfiguration",                // Port of MailFailoverTransportTest::testGetFailoverTransportWithUpstream6StyleMailConfiguration
		"MailLogTransportTest::testGetLogTransportWithConfiguredChannel",                                       // Port of MailLogTransportTest::testGetLogTransportWithConfiguredChannel
		"MailLogTransportTest::testItDecodesTheMessageBeforeLogging",                                           // Port of MailLogTransportTest::testItDecodesTheMessageBeforeLogging
		"MailLogTransportTest::testItOnlyDecodesQuotedPrintablePartsOfTheMessageBeforeLogging",                 // Port of MailLogTransportTest::testItOnlyDecodesQuotedPrintablePartsOfTheMessageBeforeLogging
		"MailLogTransportTest::testGetLogTransportWithPsrLogger",                                               // Port of MailLogTransportTest::testGetLogTransportWithPsrLogger
		"MailMailableAssertionsTest::testMailableAssertSeeInTextPassesWhenPresent",                             // Port of MailMailableAssertionsTest::testMailableAssertSeeInTextPassesWhenPresent
		"MailMailableAssertionsTest::testMailableAssertSeeInTextFailsWhenAbsent",                               // Port of MailMailableAssertionsTest::testMailableAssertSeeInTextFailsWhenAbsent
		"MailMailableAssertionsTest::testMailableAssertDontSeeInTextPassesWhenAbsent",                          // Port of MailMailableAssertionsTest::testMailableAssertDontSeeInTextPassesWhenAbsent
		"MailMailableAssertionsTest::testMailableAssertDontSeeInTextFailsWhenPresent",                          // Port of MailMailableAssertionsTest::testMailableAssertDontSeeInTextFailsWhenPresent
		"MailMailableAssertionsTest::testMailableAssertSeeInHtmlPassesWhenPresent",                             // Port of MailMailableAssertionsTest::testMailableAssertSeeInHtmlPassesWhenPresent
		"MailMailableAssertionsTest::testMailableAssertSeeInHtmlFailsWhenAbsent",                               // Port of MailMailableAssertionsTest::testMailableAssertSeeInHtmlFailsWhenAbsent
		"MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlPassesWhenAbsent",                          // Port of MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlPassesWhenAbsent
		"MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlEscapedFailsWhenPresent",                   // Port of MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlEscapedFailsWhenPresent
		"MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlUnescapedFailsWhenPresent",                 // Port of MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlUnescapedFailsWhenPresent
		"MailMailableAssertionsTest::testMailableAssertSeeInOrderTextPassesWhenPresentInOrder",                 // Port of MailMailableAssertionsTest::testMailableAssertSeeInOrderTextPassesWhenPresentInOrder
		"MailMailableAssertionsTest::testMailableAssertSeeInOrderTextFailsWhenAbsentInOrder",                   // Port of MailMailableAssertionsTest::testMailableAssertSeeInOrderTextFailsWhenAbsentInOrder
		"MailMailableAssertionsTest::testMailableAssertInOrderHtmlPassesWhenPresentInOrder",                    // Port of MailMailableAssertionsTest::testMailableAssertInOrderHtmlPassesWhenPresentInOrder
		"MailMailableAssertionsTest::testMailableAssertInOrderHtmlFailsWhenAbsentInOrder",                      // Port of MailMailableAssertionsTest::testMailableAssertInOrderHtmlFailsWhenAbsentInOrder
		"MailMailableAssertionsTest::testMailableAssertSeeInTextWithApostrophePassesWhenPresent",               // Port of MailMailableAssertionsTest::testMailableAssertSeeInTextWithApostrophePassesWhenPresent
		"MailMailableAssertionsTest::testMailableAssertSeeInTextWithApostropheFailsWhenAbsent",                 // Port of MailMailableAssertionsTest::testMailableAssertSeeInTextWithApostropheFailsWhenAbsent
		"MailMailableAssertionsTest::testMailableAssertDontSeeInTextWithApostrophePassesWhenAbsent",            // Port of MailMailableAssertionsTest::testMailableAssertDontSeeInTextWithApostrophePassesWhenAbsent
		"MailMailableAssertionsTest::testMailableAssertDontSeeInTextWithApostropheFailsWhenPresent",            // Port of MailMailableAssertionsTest::testMailableAssertDontSeeInTextWithApostropheFailsWhenPresent
		"MailMailableAssertionsTest::testMailableAssertSeeInHtmlWithApostropheFailsWhenAbsent",                 // Port of MailMailableAssertionsTest::testMailableAssertSeeInHtmlWithApostropheFailsWhenAbsent
		"MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlWithApostrophePassesWhenAbsent",            // Port of MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlWithApostrophePassesWhenAbsent
		"MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlWithApostropheFailsWhenPresent",            // Port of MailMailableAssertionsTest::testMailableAssertDontSeeInHtmlWithApostropheFailsWhenPresent
		"MailMailableAssertionsTest::testMailableAssertSeeInHtmlWithBladeEscapedApostrophePassesWhenPresent",   // Port of MailMailableAssertionsTest::testMailableAssertSeeInHtmlWithBladeEscapedApostrophePassesWhenPresent
		"MailMailableAssertionsTest::testMailableAssertSeeInOrderInHtmlWithApostrophePassesWhenPresentInOrder", // Port of MailMailableAssertionsTest::testMailableAssertSeeInOrderInHtmlWithApostrophePassesWhenPresentInOrder
		"MailMailableAssertionsTest::testMailableAssertSeeInOrderInHtmlWithApostropheFailsWhenAbsentInOrder",   // Port of MailMailableAssertionsTest::testMailableAssertSeeInOrderInHtmlWithApostropheFailsWhenAbsentInOrder
		"MailMailableDataTest::testMailableDataIsNotLost",                                                      // Port of MailMailableDataTest::testMailableDataIsNotLost
		"MailMailableHeadersTest::test",                                                                        // Port of MailMailableHeadersTest::test
		"MailMailableTest::testMailableSetsRecipientsCorrectly",                                                // Port of MailMailableTest::testMailableSetsRecipientsCorrectly
		"MailMailableTest::testMailableSetsCcRecipientsCorrectly",                                              // Port of MailMailableTest::testMailableSetsCcRecipientsCorrectly
		"MailMailableTest::testMailableSetsBccRecipientsCorrectly",                                             // Port of MailMailableTest::testMailableSetsBccRecipientsCorrectly
		"MailMailableTest::testMailableSetsReplyToCorrectly",                                                   // Port of MailMailableTest::testMailableSetsReplyToCorrectly
		"MailMailableTest::testMailableSetsFromCorrectly",                                                      // Port of MailMailableTest::testMailableSetsFromCorrectly
		"MailMailableTest::testMailableSetsSubjectCorrectly",                                                   // Port of MailMailableTest::testMailableSetsSubjectCorrectly
		"MailMailableTest::testItIgnoresDuplicatedRawAttachments",                                              // Port of MailMailableTest::testItIgnoresDuplicatedRawAttachments
		"MailMailableTest::testItIgnoresDuplicateStorageAttachments",                                           // Port of MailMailableTest::testItIgnoresDuplicateStorageAttachments
		"MailMailableTest::testMailableBuildsViewData",                                                         // Port of MailMailableTest::testMailableBuildsViewData
		"MailMailableTest::testMailerMayBeSet",                                                                 // Port of MailMailableTest::testMailerMayBeSet
		"MailMailableTest::testMailablePriorityGetsSent",                                                       // Port of MailMailableTest::testMailablePriorityGetsSent
		"MailMailableTest::testMailableMetadataGetsSent",                                                       // Port of MailMailableTest::testMailableMetadataGetsSent
		"MailMailableTest::testMailableMergeMetadata",                                                          // Port of MailMailableTest::testMailableMergeMetadata
		"MailMailableTest::testMailableTagGetsSent",                                                            // Port of MailMailableTest::testMailableTagGetsSent
		"MailMailableTest::testItCanAttachMultipleFiles",                                                       // Port of MailMailableTest::testItCanAttachMultipleFiles
		"MailMailableTest::testItAttachesFilesViaAttachableContractFromPath",                                   // Port of MailMailableTest::testItAttachesFilesViaAttachableContractFromPath
		"MailMailableTest::testItAttachesFilesViaAttachableContractFromData",                                   // Port of MailMailableTest::testItAttachesFilesViaAttachableContractFromData
		"MailMailableTest::testItCanJitNameAttachments",                                                        // Port of MailMailableTest::testItCanJitNameAttachments
		"MailMailableTest::testHasAttachmentWithJitNamedAttachment",                                            // Port of MailMailableTest::testHasAttachmentWithJitNamedAttachment
		"MailMailableTest::testHasAttachmentWithEnvelopeAttachments",                                           // Port of MailMailableTest::testHasAttachmentWithEnvelopeAttachments
		"MailMailableTest::testItCanCheckForPathBasedAttachments",                                              // Port of MailMailableTest::testItCanCheckForPathBasedAttachments
		"MailMailableTest::testItCanCheckForAttachmentBasedAttachments",                                        // Port of MailMailableTest::testItCanCheckForAttachmentBasedAttachments
		"MailMailableTest::testItCanCheckForAttachableBasedAttachments",                                        // Port of MailMailableTest::testItCanCheckForAttachableBasedAttachments
		"MailMailableTest::testItCanCheckForDataBasedAttachments",                                              // Port of MailMailableTest::testItCanCheckForDataBasedAttachments
		"MailMailableTest::testItCanCheckForStorageBasedAttachments",                                           // Port of MailMailableTest::testItCanCheckForStorageBasedAttachments
		"MailMailableTest::testAssertHasNoAttachments",                                                         // Port of MailMailableTest::testAssertHasNoAttachments
		"MailMailableTest::testAssertHasAttachment",                                                            // Port of MailMailableTest::testAssertHasAttachment
		"MailMailableTest::testAssertHasAttachedData",                                                          // Port of MailMailableTest::testAssertHasAttachedData
		"MailMailableTest::testAssertHasAttachmentFromStorage",                                                 // Port of MailMailableTest::testAssertHasAttachmentFromStorage
		"MailMailableTest::testAssertHasSubject",                                                               // Port of MailMailableTest::testAssertHasSubject
		"MailMailableTest::testMailableHeadersGetSent",                                                         // Port of MailMailableTest::testMailableHeadersGetSent
		"MailMailableTest::testMailableAttributesInBuild",                                                      // Port of MailMailableTest::testMailableAttributesInBuild
		"MailMailableTest::testMailablesCanBeTapped",                                                           // Port of MailMailableTest::testMailablesCanBeTapped
		"MailMailerTest::testMailerSendSendsMessageWithProperViewContent",                                      // Port of MailMailerTest::testMailerSendSendsMessageWithProperViewContent
		"MailMailerTest::testMailerSendSendsMessageWithCcAndBccRecipients",                                     // Port of MailMailerTest::testMailerSendSendsMessageWithCcAndBccRecipients
		"MailMailerTest::testMailerSendSendsMessageWithProperViewContentUsingHtmlStrings",                      // Port of MailMailerTest::testMailerSendSendsMessageWithProperViewContentUsingHtmlStrings
		"MailMailerTest::testMailerSendSendsMessageWithProperViewContentUsingStringCallbacks",                  // Port of MailMailerTest::testMailerSendSendsMessageWithProperViewContentUsingStringCallbacks
		"MailMailerTest::testMailerSendSendsMessageWithProperViewContentUsingHtmlMethod",                       // Port of MailMailerTest::testMailerSendSendsMessageWithProperViewContentUsingHtmlMethod
		"MailMailerTest::testMailerSendSendsMessageWithProperPlainViewContent",                                 // Port of MailMailerTest::testMailerSendSendsMessageWithProperPlainViewContent
		"MailMailerTest::testMailerSendSendsMessageWithProperPlainViewContentWhenExplicit",                     // Port of MailMailerTest::testMailerSendSendsMessageWithProperPlainViewContentWhenExplicit
		"MailMailerTest::testToAllowsEmailAndName",                                                             // Port of MailMailerTest::testToAllowsEmailAndName
		"MailMailerTest::testGlobalFromIsRespectedOnAllMessages",                                               // Port of MailMailerTest::testGlobalFromIsRespectedOnAllMessages
		"MailMailerTest::testGlobalReplyToIsRespectedOnAllMessages",                                            // Port of MailMailerTest::testGlobalReplyToIsRespectedOnAllMessages
		"MailMailerTest::testGlobalToIsRespectedOnAllMessages",                                                 // Port of MailMailerTest::testGlobalToIsRespectedOnAllMessages
		"MailMailerTest::testGlobalReturnPathIsRespectedOnAllMessages",                                         // Port of MailMailerTest::testGlobalReturnPathIsRespectedOnAllMessages
		"MailMailerTest::testEventsAreDispatched",                                                              // Port of MailMailerTest::testEventsAreDispatched
		"MailMailerTest::testMacroable",                                                                        // Port of MailMailerTest::testMacroable
		"MailManagerTest::testEmptyTransportConfig",                                                            // Port of MailManagerTest::testEmptyTransportConfig
		"MailManagerTest::testMailUrlConfig",                                                                   // Port of MailManagerTest::testMailUrlConfig
		"MailManagerTest::testMailUrlConfigWithAutoTls",                                                        // Port of MailManagerTest::testMailUrlConfigWithAutoTls
		"MailManagerTest::testMailUrlConfigWithAutoTlsDisabled",                                                // Port of MailManagerTest::testMailUrlConfigWithAutoTlsDisabled
		"MailManagerTest::testBuild",                                                                           // Port of MailManagerTest::testBuild
		"MailManagerTest::testMailManagerCanResolveBackedEnumMailer",                                           // Port of MailManagerTest::testMailManagerCanResolveBackedEnumMailer
		"MailManagerTest::testMailManagerCanResolveBackedEnumDriver",                                           // Port of MailManagerTest::testMailManagerCanResolveBackedEnumDriver
		"MailManagerTest::testPurgeAcceptsBackedEnum",                                                          // Port of MailManagerTest::testPurgeAcceptsBackedEnum
		"MailMessageTest::testFromMethod",                                                                      // Port of MailMessageTest::testFromMethod
		"MailMessageTest::testSenderMethod",                                                                    // Port of MailMessageTest::testSenderMethod
		"MailMessageTest::testReturnPathMethod",                                                                // Port of MailMessageTest::testReturnPathMethod
		"MailMessageTest::testToMethod",                                                                        // Port of MailMessageTest::testToMethod
		"MailMessageTest::testToMethodWithOverride",                                                            // Port of MailMessageTest::testToMethodWithOverride
		"MailMessageTest::testCcMethod",                                                                        // Port of MailMessageTest::testCcMethod
		"MailMessageTest::testBccMethod",                                                                       // Port of MailMessageTest::testBccMethod
		"MailMessageTest::testReplyToMethod",                                                                   // Port of MailMessageTest::testReplyToMethod
		"MailMessageTest::testSubjectMethod",                                                                   // Port of MailMessageTest::testSubjectMethod
		"MailMessageTest::testPriorityMethod",                                                                  // Port of MailMessageTest::testPriorityMethod
		"MailMessageTest::testBasicAttachment",                                                                 // Port of MailMessageTest::testBasicAttachment
		"MailMessageTest::testDataAttachment",                                                                  // Port of MailMessageTest::testDataAttachment
		"MailMessageTest::testItAttachesFilesViaAttachableContractFromPath",                                    // Port of MailMessageTest::testItAttachesFilesViaAttachableContractFromPath
		"MailMessageTest::testItAttachesFilesViaAttachableContractFromData",                                    // Port of MailMessageTest::testItAttachesFilesViaAttachableContractFromData
		"MailMessageTest::testEmbedPath",                                                                       // Port of MailMessageTest::testEmbedPath
		"MailMessageTest::testDataEmbed",                                                                       // Port of MailMessageTest::testDataEmbed
		"MailMessageTest::testItEmbedsFilesViaAttachableContractFromPath",                                      // Port of MailMessageTest::testItEmbedsFilesViaAttachableContractFromPath
		"MailMessageTest::testItGeneratesARandomNameWhenAttachableHasNone",                                     // Port of MailMessageTest::testItGeneratesARandomNameWhenAttachableHasNone
		"MailRoundRobinTransportTest::testGetRoundRobinTransportWithConfiguredTransports",                      // Port of MailRoundRobinTransportTest::testGetRoundRobinTransportWithConfiguredTransports
		"MailRoundRobinTransportTest::testGetRoundRobinTransportWithUpstream6StyleMailConfiguration",            // Port of MailRoundRobinTransportTest::testGetRoundRobinTransportWithUpstream6StyleMailConfiguration
		"MailSesTransportTest::testGetTransport",                                                               // Port of MailSesTransportTest::testGetTransport
		"MailSesTransportTest::testSend",                                                                       // Port of MailSesTransportTest::testSend
		"MailSesTransportTest::testSendError",                                                                  // Port of MailSesTransportTest::testSendError
		"MailSesTransportTest::testSesLocalConfiguration",                                                      // Port of MailSesTransportTest::testSesLocalConfiguration
		"MailSesV2TransportTest::testGetTransport",                                                             // Port of MailSesV2TransportTest::testGetTransport
		"MailSesV2TransportTest::testSend",                                                                     // Port of MailSesV2TransportTest::testSend
		"MailSesV2TransportTest::testSendError",                                                                // Port of MailSesV2TransportTest::testSendError
		"MailSesV2TransportTest::testSesV2LocalConfiguration",                                                  // Port of MailSesV2TransportTest::testSesV2LocalConfiguration
		"MailableAlternativeSyntaxTest::testBasicMailableInspection",                                           // Port of MailableAlternativeSyntaxTest::testBasicMailableInspection
		"MailableAlternativeSyntaxTest::testEnvelopesCanReceiveAdditionalRecipients",                           // Port of MailableAlternativeSyntaxTest::testEnvelopesCanReceiveAdditionalRecipients
		"MailableQueuedTest::testQueuedMailableSent",                                                           // Port of MailableQueuedTest::testQueuedMailableSent
		"MailableQueuedTest::testQueuedMailableWithAttachmentSent",                                             // Port of MailableQueuedTest::testQueuedMailableWithAttachmentSent
		"MailableQueuedTest::testQueuedMailableWithAttachmentFromDiskSent",                                     // Port of MailableQueuedTest::testQueuedMailableWithAttachmentFromDiskSent
		"MailableQueuedTest::testQueuedMailableForwardsMessageGroupFromMethodToQueueJob",                       // Port of MailableQueuedTest::testQueuedMailableForwardsMessageGroupFromMethodToQueueJob
		"MailableQueuedTest::testQueuedMailableForwardsMessageGroupFromPropertyOverridingMethodToQueueJob",     // Port of MailableQueuedTest::testQueuedMailableForwardsMessageGroupFromPropertyOverridingMethodToQueueJob
		"MailableQueuedTest::testQueuedMailableForwardsDeduplicatorToQueueJob",                                 // Port of MailableQueuedTest::testQueuedMailableForwardsDeduplicatorToQueueJob
		"MailableQueuedTest::testQueuedMailableRespectsDelayAttribute",                                         // Port of MailableQueuedTest::testQueuedMailableRespectsDelayAttribute
		"MailableQueuedTest::testQueuedMailableDelayPropertyOverridesAttribute",                                // Port of MailableQueuedTest::testQueuedMailableDelayPropertyOverridesAttribute
		"MailableQueuedTest::testQueuedMailableForwardsDeduplicationIdMethodToQueueJob",                        // Port of MailableQueuedTest::testQueuedMailableForwardsDeduplicationIdMethodToQueueJob
	}

	if len(ported) != 135 {
		t.Fatalf("expected 135 Upstream inventory entries, got %d", len(ported))
	}
}
