export interface CurrencyDefinition {
  readonly decimal: string;
  readonly thousand: string;
  readonly code: CurrencyCode;
  readonly fraction: number;
  readonly numericCode: string;
  readonly grapheme: string;
  readonly template: string;
}

export interface CurrencySymbol {
  readonly id: string;
  readonly currency: CurrencyCode;
}

export const AED = "AED" as const;
export const AFN = "AFN" as const;
export const ALL = "ALL" as const;
export const AMD = "AMD" as const;
export const ANG = "ANG" as const;
export const AOA = "AOA" as const;
export const ARS = "ARS" as const;
export const AUD = "AUD" as const;
export const AWG = "AWG" as const;
export const AZN = "AZN" as const;
export const BAM = "BAM" as const;
export const BBD = "BBD" as const;
export const BDT = "BDT" as const;
export const BGN = "BGN" as const;
export const BHD = "BHD" as const;
export const BIF = "BIF" as const;
export const BMD = "BMD" as const;
export const BND = "BND" as const;
export const BOB = "BOB" as const;
export const BOV = "BOV" as const;
export const BRL = "BRL" as const;
export const BSD = "BSD" as const;
export const BTN = "BTN" as const;
export const BWP = "BWP" as const;
export const BYN = "BYN" as const;
export const BZD = "BZD" as const;
export const CAD = "CAD" as const;
export const CDF = "CDF" as const;
export const CHE = "CHE" as const;
export const CHF = "CHF" as const;
export const CHW = "CHW" as const;
export const CLF = "CLF" as const;
export const CLP = "CLP" as const;
export const CNY = "CNY" as const;
export const COP = "COP" as const;
export const COU = "COU" as const;
export const CRC = "CRC" as const;
export const CUC = "CUC" as const;
export const CUP = "CUP" as const;
export const CVE = "CVE" as const;
export const CZK = "CZK" as const;
export const DJF = "DJF" as const;
export const DKK = "DKK" as const;
export const DOP = "DOP" as const;
export const DZD = "DZD" as const;
export const EGP = "EGP" as const;
export const ERN = "ERN" as const;
export const ETB = "ETB" as const;
export const EUR = "EUR" as const;
export const FJD = "FJD" as const;
export const FKP = "FKP" as const;
export const GBP = "GBP" as const;
export const GEL = "GEL" as const;
export const GHS = "GHS" as const;
export const GIP = "GIP" as const;
export const GMD = "GMD" as const;
export const GNF = "GNF" as const;
export const GTQ = "GTQ" as const;
export const GYD = "GYD" as const;
export const HKD = "HKD" as const;
export const HNL = "HNL" as const;
export const HTG = "HTG" as const;
export const HUF = "HUF" as const;
export const IDR = "IDR" as const;
export const ILS = "ILS" as const;
export const INR = "INR" as const;
export const IQD = "IQD" as const;
export const IRR = "IRR" as const;
export const ISK = "ISK" as const;
export const JMD = "JMD" as const;
export const JOD = "JOD" as const;
export const JPY = "JPY" as const;
export const KES = "KES" as const;
export const KGS = "KGS" as const;
export const KHR = "KHR" as const;
export const KMF = "KMF" as const;
export const KPW = "KPW" as const;
export const KRW = "KRW" as const;
export const KWD = "KWD" as const;
export const KYD = "KYD" as const;
export const KZT = "KZT" as const;
export const LAK = "LAK" as const;
export const LBP = "LBP" as const;
export const LKR = "LKR" as const;
export const LRD = "LRD" as const;
export const LSL = "LSL" as const;
export const LYD = "LYD" as const;
export const MAD = "MAD" as const;
export const MDL = "MDL" as const;
export const MGA = "MGA" as const;
export const MKD = "MKD" as const;
export const MMK = "MMK" as const;
export const MNT = "MNT" as const;
export const MOP = "MOP" as const;
export const MUR = "MUR" as const;
export const MRU = "MRU" as const;
export const MVR = "MVR" as const;
export const MWK = "MWK" as const;
export const MXN = "MXN" as const;
export const MXV = "MXV" as const;
export const MYR = "MYR" as const;
export const MZN = "MZN" as const;
export const NAD = "NAD" as const;
export const NGN = "NGN" as const;
export const NIO = "NIO" as const;
export const NOK = "NOK" as const;
export const NPR = "NPR" as const;
export const NZD = "NZD" as const;
export const OMR = "OMR" as const;
export const PAB = "PAB" as const;
export const PEN = "PEN" as const;
export const PGK = "PGK" as const;
export const PHP = "PHP" as const;
export const PKR = "PKR" as const;
export const PLN = "PLN" as const;
export const PYG = "PYG" as const;
export const QAR = "QAR" as const;
export const RON = "RON" as const;
export const RSD = "RSD" as const;
export const RUB = "RUB" as const;
export const RWF = "RWF" as const;
export const SAR = "SAR" as const;
export const SBD = "SBD" as const;
export const SCR = "SCR" as const;
export const SDG = "SDG" as const;
export const SEK = "SEK" as const;
export const SGD = "SGD" as const;
export const SHP = "SHP" as const;
export const SLE = "SLE" as const;
export const SLL = "SLL" as const;
export const SOS = "SOS" as const;
export const SRD = "SRD" as const;
export const SSP = "SSP" as const;
export const STN = "STN" as const;
export const SVC = "SVC" as const;
export const SYP = "SYP" as const;
export const SZL = "SZL" as const;
export const THB = "THB" as const;
export const TJS = "TJS" as const;
export const TMT = "TMT" as const;
export const TND = "TND" as const;
export const TOP = "TOP" as const;
export const TRY = "TRY" as const;
export const TTD = "TTD" as const;
export const TWD = "TWD" as const;
export const TZS = "TZS" as const;
export const UAH = "UAH" as const;
export const UGX = "UGX" as const;
export const USD = "USD" as const;
export const USN = "USN" as const;
export const UYI = "UYI" as const;
export const UYU = "UYU" as const;
export const UYW = "UYW" as const;
export const UZS = "UZS" as const;
export const VES = "VES" as const;
export const VND = "VND" as const;
export const VUV = "VUV" as const;
export const WST = "WST" as const;
export const XAF = "XAF" as const;
export const XAG = "XAG" as const;
export const XAU = "XAU" as const;
export const XBA = "XBA" as const;
export const XBB = "XBB" as const;
export const XBC = "XBC" as const;
export const XBD = "XBD" as const;
export const XCD = "XCD" as const;
export const XDR = "XDR" as const;
export const XOF = "XOF" as const;
export const XPD = "XPD" as const;
export const XPF = "XPF" as const;
export const XPT = "XPT" as const;
export const XSU = "XSU" as const;
export const XTS = "XTS" as const;
export const XUA = "XUA" as const;
export const XXX = "XXX" as const;
export const YER = "YER" as const;
export const ZAR = "ZAR" as const;
export const ZMW = "ZMW" as const;
export const ZWL = "ZWL" as const;

export const currencyCodes = [
  AED,
  AFN,
  ALL,
  AMD,
  ANG,
  AOA,
  ARS,
  AUD,
  AWG,
  AZN,
  BAM,
  BBD,
  BDT,
  BGN,
  BHD,
  BIF,
  BMD,
  BND,
  BOB,
  BOV,
  BRL,
  BSD,
  BTN,
  BWP,
  BYN,
  BZD,
  CAD,
  CDF,
  CHE,
  CHF,
  CHW,
  CLF,
  CLP,
  CNY,
  COP,
  COU,
  CRC,
  CUC,
  CUP,
  CVE,
  CZK,
  DJF,
  DKK,
  DOP,
  DZD,
  EGP,
  ERN,
  ETB,
  EUR,
  FJD,
  FKP,
  GBP,
  GEL,
  GHS,
  GIP,
  GMD,
  GNF,
  GTQ,
  GYD,
  HKD,
  HNL,
  HTG,
  HUF,
  IDR,
  ILS,
  INR,
  IQD,
  IRR,
  ISK,
  JMD,
  JOD,
  JPY,
  KES,
  KGS,
  KHR,
  KMF,
  KPW,
  KRW,
  KWD,
  KYD,
  KZT,
  LAK,
  LBP,
  LKR,
  LRD,
  LSL,
  LYD,
  MAD,
  MDL,
  MGA,
  MKD,
  MMK,
  MNT,
  MOP,
  MUR,
  MRU,
  MVR,
  MWK,
  MXN,
  MXV,
  MYR,
  MZN,
  NAD,
  NGN,
  NIO,
  NOK,
  NPR,
  NZD,
  OMR,
  PAB,
  PEN,
  PGK,
  PHP,
  PKR,
  PLN,
  PYG,
  QAR,
  RON,
  RSD,
  RUB,
  RWF,
  SAR,
  SBD,
  SCR,
  SDG,
  SEK,
  SGD,
  SHP,
  SLE,
  SLL,
  SOS,
  SRD,
  SSP,
  STN,
  SVC,
  SYP,
  SZL,
  THB,
  TJS,
  TMT,
  TND,
  TOP,
  TRY,
  TTD,
  TWD,
  TZS,
  UAH,
  UGX,
  USD,
  USN,
  UYI,
  UYU,
  UYW,
  UZS,
  VES,
  VND,
  VUV,
  WST,
  XAF,
  XAG,
  XAU,
  XBA,
  XBB,
  XBC,
  XBD,
  XCD,
  XDR,
  XOF,
  XPD,
  XPF,
  XPT,
  XSU,
  XTS,
  XUA,
  XXX,
  YER,
  ZAR,
  ZMW,
  ZWL,
] as const;

export type CurrencyCode = (typeof currencyCodes)[number];

export const currencySymbols: readonly CurrencySymbol[] = [
  { id: "CFP", currency: XPF },
  { id: "NT$", currency: TWD },
  { id: "R$", currency: BRL },
  { id: "C$", currency: CAD },
  { id: "A$", currency: AUD },
  { id: "S$", currency: SGD },
  { id: "HK$", currency: HKD },
  { id: "$", currency: USD },
  { id: "€", currency: EUR },
  { id: "£", currency: GBP },
  { id: "¥", currency: JPY },
  { id: "₹", currency: INR },
  { id: "₣", currency: CHF },
] as const;

export const currencyDefinitions: Record<CurrencyCode, CurrencyDefinition> = {
  AED: {
    decimal: ".",
    thousand: ",",
    code: AED,
    fraction: 2,
    numericCode: "784",
    grapheme: ".\u062f.\u0625",
    template: "1 $",
  },
  AFN: {
    decimal: ".",
    thousand: ",",
    code: AFN,
    fraction: 2,
    numericCode: "971",
    grapheme: "\u060b",
    template: "1 $",
  },
  ALL: {
    decimal: ".",
    thousand: ",",
    code: ALL,
    fraction: 2,
    numericCode: "008",
    grapheme: "L",
    template: "$1",
  },
  AMD: {
    decimal: ".",
    thousand: ",",
    code: AMD,
    fraction: 2,
    numericCode: "051",
    grapheme: "\u0564\u0580.",
    template: "1 $",
  },
  ANG: {
    decimal: ",",
    thousand: ".",
    code: ANG,
    fraction: 2,
    numericCode: "532",
    grapheme: "\u0192",
    template: "$1",
  },
  AOA: {
    decimal: ".",
    thousand: ",",
    code: AOA,
    fraction: 2,
    numericCode: "973",
    grapheme: "Kz",
    template: "1$",
  },
  ARS: {
    decimal: ",",
    thousand: ".",
    code: ARS,
    fraction: 2,
    numericCode: "032",
    grapheme: "$",
    template: "$1",
  },
  AUD: {
    decimal: ".",
    thousand: ",",
    code: AUD,
    fraction: 2,
    numericCode: "036",
    grapheme: "A$",
    template: "$1",
  },
  AWG: {
    decimal: ".",
    thousand: ",",
    code: AWG,
    fraction: 2,
    numericCode: "533",
    grapheme: "\u0192",
    template: "1$",
  },
  AZN: {
    decimal: ".",
    thousand: ",",
    code: AZN,
    fraction: 2,
    numericCode: "944",
    grapheme: "\u20bc",
    template: "$1",
  },
  BAM: {
    decimal: ".",
    thousand: ",",
    code: BAM,
    fraction: 2,
    numericCode: "977",
    grapheme: "KM",
    template: "$1",
  },
  BBD: {
    decimal: ".",
    thousand: ",",
    code: BBD,
    fraction: 2,
    numericCode: "052",
    grapheme: "$",
    template: "$1",
  },
  BDT: {
    decimal: ".",
    thousand: ",",
    code: BDT,
    fraction: 2,
    numericCode: "050",
    grapheme: "\u09f3",
    template: "$1",
  },
  BGN: {
    decimal: ".",
    thousand: ",",
    code: BGN,
    fraction: 2,
    numericCode: "975",
    grapheme: "\u043b\u0432",
    template: "$1",
  },
  BHD: {
    decimal: ".",
    thousand: ",",
    code: BHD,
    fraction: 3,
    numericCode: "048",
    grapheme: ".\u062f.\u0628",
    template: "1 $",
  },
  BIF: {
    decimal: ".",
    thousand: ",",
    code: BIF,
    fraction: 0,
    numericCode: "108",
    grapheme: "Fr",
    template: "1$",
  },
  BMD: {
    decimal: ".",
    thousand: ",",
    code: BMD,
    fraction: 2,
    numericCode: "060",
    grapheme: "$",
    template: "$1",
  },
  BND: {
    decimal: ".",
    thousand: ",",
    code: BND,
    fraction: 2,
    numericCode: "096",
    grapheme: "$",
    template: "$1",
  },
  BOB: {
    decimal: ".",
    thousand: ",",
    code: BOB,
    fraction: 2,
    numericCode: "068",
    grapheme: "Bs.",
    template: "$1",
  },
  BOV: {
    decimal: ".",
    thousand: ",",
    code: BOV,
    fraction: 2,
    numericCode: "984",
    grapheme: "BOV",
    template: "1 $",
  },
  BRL: {
    decimal: ",",
    thousand: ".",
    code: BRL,
    fraction: 2,
    numericCode: "986",
    grapheme: "R$",
    template: "$1",
  },
  BSD: {
    decimal: ".",
    thousand: ",",
    code: BSD,
    fraction: 2,
    numericCode: "044",
    grapheme: "$",
    template: "$1",
  },
  BTN: {
    decimal: ".",
    thousand: ",",
    code: BTN,
    fraction: 2,
    numericCode: "064",
    grapheme: "Nu.",
    template: "1$",
  },
  BWP: {
    decimal: ".",
    thousand: ",",
    code: BWP,
    fraction: 2,
    numericCode: "072",
    grapheme: "P",
    template: "$1",
  },
  BYN: {
    decimal: ",",
    thousand: " ",
    code: BYN,
    fraction: 2,
    numericCode: "933",
    grapheme: "p.",
    template: "1 $",
  },
  BZD: {
    decimal: ".",
    thousand: ",",
    code: BZD,
    fraction: 2,
    numericCode: "084",
    grapheme: "BZ$",
    template: "$1",
  },
  CAD: {
    decimal: ".",
    thousand: ",",
    code: CAD,
    fraction: 2,
    numericCode: "124",
    grapheme: "$",
    template: "$1",
  },
  CDF: {
    decimal: ".",
    thousand: ",",
    code: CDF,
    fraction: 2,
    numericCode: "976",
    grapheme: "FC",
    template: "1$",
  },
  CHE: {
    decimal: ".",
    thousand: ",",
    code: CHE,
    fraction: 2,
    numericCode: "947",
    grapheme: "CHE",
    template: "1 $",
  },
  CHF: {
    decimal: ".",
    thousand: ",",
    code: CHF,
    fraction: 2,
    numericCode: "756",
    grapheme: "CHF",
    template: "1 $",
  },
  CHW: {
    decimal: ".",
    thousand: ",",
    code: CHW,
    fraction: 2,
    numericCode: "948",
    grapheme: "CHW",
    template: "1 $",
  },
  CLF: {
    decimal: ",",
    thousand: ".",
    code: CLF,
    fraction: 4,
    numericCode: "990",
    grapheme: "UF",
    template: "$1",
  },
  CLP: {
    decimal: ",",
    thousand: ".",
    code: CLP,
    fraction: 0,
    numericCode: "152",
    grapheme: "$",
    template: "$1",
  },
  CNY: {
    decimal: ".",
    thousand: ",",
    code: CNY,
    fraction: 2,
    numericCode: "156",
    grapheme: "\u5143",
    template: "1 $",
  },
  COP: {
    decimal: ",",
    thousand: ".",
    code: COP,
    fraction: 2,
    numericCode: "170",
    grapheme: "$",
    template: "$1",
  },
  COU: {
    decimal: ".",
    thousand: ",",
    code: COU,
    fraction: 2,
    numericCode: "970",
    grapheme: "COU",
    template: "1 $",
  },
  CRC: {
    decimal: ".",
    thousand: ",",
    code: CRC,
    fraction: 2,
    numericCode: "188",
    grapheme: "\u20a1",
    template: "$1",
  },
  CUC: {
    decimal: ".",
    thousand: ",",
    code: CUC,
    fraction: 2,
    numericCode: "931",
    grapheme: "$",
    template: "1$",
  },
  CUP: {
    decimal: ".",
    thousand: ",",
    code: CUP,
    fraction: 2,
    numericCode: "192",
    grapheme: "$MN",
    template: "$1",
  },
  CVE: {
    decimal: ".",
    thousand: ",",
    code: CVE,
    fraction: 2,
    numericCode: "132",
    grapheme: "$",
    template: "1$",
  },
  CZK: {
    decimal: ".",
    thousand: ",",
    code: CZK,
    fraction: 2,
    numericCode: "203",
    grapheme: "K\u010d",
    template: "1 $",
  },
  DJF: {
    decimal: ".",
    thousand: ",",
    code: DJF,
    fraction: 0,
    numericCode: "262",
    grapheme: "Fdj",
    template: "1 $",
  },
  DKK: {
    decimal: ",",
    thousand: ".",
    code: DKK,
    fraction: 2,
    numericCode: "208",
    grapheme: "kr",
    template: "$ 1",
  },
  DOP: {
    decimal: ".",
    thousand: ",",
    code: DOP,
    fraction: 2,
    numericCode: "214",
    grapheme: "RD$",
    template: "$1",
  },
  DZD: {
    decimal: ".",
    thousand: ",",
    code: DZD,
    fraction: 2,
    numericCode: "012",
    grapheme: ".\u062f.\u062c",
    template: "1 $",
  },
  EGP: {
    decimal: ".",
    thousand: ",",
    code: EGP,
    fraction: 2,
    numericCode: "818",
    grapheme: "\u00a3",
    template: "$1",
  },
  ERN: {
    decimal: ".",
    thousand: ",",
    code: ERN,
    fraction: 2,
    numericCode: "232",
    grapheme: "Nfk",
    template: "1 $",
  },
  ETB: {
    decimal: ".",
    thousand: ",",
    code: ETB,
    fraction: 2,
    numericCode: "230",
    grapheme: "Br",
    template: "1 $",
  },
  EUR: {
    decimal: ".",
    thousand: ",",
    code: EUR,
    fraction: 2,
    numericCode: "978",
    grapheme: "\u20ac",
    template: "$1",
  },
  FJD: {
    decimal: ".",
    thousand: ",",
    code: FJD,
    fraction: 2,
    numericCode: "242",
    grapheme: "$",
    template: "$1",
  },
  FKP: {
    decimal: ".",
    thousand: ",",
    code: FKP,
    fraction: 2,
    numericCode: "238",
    grapheme: "\u00a3",
    template: "$1",
  },
  GBP: {
    decimal: ".",
    thousand: ",",
    code: GBP,
    fraction: 2,
    numericCode: "826",
    grapheme: "\u00a3",
    template: "$1",
  },
  GEL: {
    decimal: ".",
    thousand: ",",
    code: GEL,
    fraction: 2,
    numericCode: "981",
    grapheme: "\u10da",
    template: "1 $",
  },
  GHS: {
    decimal: ".",
    thousand: ",",
    code: GHS,
    fraction: 2,
    numericCode: "936",
    grapheme: "\u20b5",
    template: "$1",
  },
  GIP: {
    decimal: ".",
    thousand: ",",
    code: GIP,
    fraction: 2,
    numericCode: "292",
    grapheme: "\u00a3",
    template: "$1",
  },
  GMD: {
    decimal: ".",
    thousand: ",",
    code: GMD,
    fraction: 2,
    numericCode: "270",
    grapheme: "D",
    template: "1 $",
  },
  GNF: {
    decimal: ".",
    thousand: ",",
    code: GNF,
    fraction: 0,
    numericCode: "324",
    grapheme: "FG",
    template: "1 $",
  },
  GTQ: {
    decimal: ".",
    thousand: ",",
    code: GTQ,
    fraction: 2,
    numericCode: "320",
    grapheme: "Q",
    template: "$1",
  },
  GYD: {
    decimal: ".",
    thousand: ",",
    code: GYD,
    fraction: 2,
    numericCode: "328",
    grapheme: "$",
    template: "$1",
  },
  HKD: {
    decimal: ".",
    thousand: ",",
    code: HKD,
    fraction: 2,
    numericCode: "344",
    grapheme: "HK$",
    template: "$1",
  },
  HNL: {
    decimal: ".",
    thousand: ",",
    code: HNL,
    fraction: 2,
    numericCode: "340",
    grapheme: "L",
    template: "$1",
  },
  HTG: {
    decimal: ",",
    thousand: ".",
    code: HTG,
    fraction: 2,
    numericCode: "332",
    grapheme: "G",
    template: "1 $",
  },
  HUF: {
    decimal: ",",
    thousand: ".",
    code: HUF,
    fraction: 2,
    numericCode: "348",
    grapheme: "Ft",
    template: "1 $",
  },
  IDR: {
    decimal: ",",
    thousand: ".",
    code: IDR,
    fraction: 2,
    numericCode: "360",
    grapheme: "Rp",
    template: "$1",
  },
  ILS: {
    decimal: ".",
    thousand: ",",
    code: ILS,
    fraction: 2,
    numericCode: "376",
    grapheme: "\u20aa",
    template: "$1",
  },
  INR: {
    decimal: ".",
    thousand: ",",
    code: INR,
    fraction: 2,
    numericCode: "356",
    grapheme: "\u20b9",
    template: "$1",
  },
  IQD: {
    decimal: ".",
    thousand: ",",
    code: IQD,
    fraction: 3,
    numericCode: "368",
    grapheme: ".\u062f.\u0639",
    template: "1 $",
  },
  IRR: {
    decimal: ".",
    thousand: ",",
    code: IRR,
    fraction: 2,
    numericCode: "364",
    grapheme: "\ufdfc",
    template: "1 $",
  },
  ISK: {
    decimal: ",",
    thousand: ".",
    code: ISK,
    fraction: 0,
    numericCode: "352",
    grapheme: "kr",
    template: "$1",
  },
  JMD: {
    decimal: ".",
    thousand: ",",
    code: JMD,
    fraction: 2,
    numericCode: "388",
    grapheme: "J$",
    template: "$1",
  },
  JOD: {
    decimal: ".",
    thousand: ",",
    code: JOD,
    fraction: 3,
    numericCode: "400",
    grapheme: ".\u062f.\u0625",
    template: "1 $",
  },
  JPY: {
    decimal: ".",
    thousand: ",",
    code: JPY,
    fraction: 0,
    numericCode: "392",
    grapheme: "\u00a5",
    template: "$1",
  },
  KES: {
    decimal: ".",
    thousand: ",",
    code: KES,
    fraction: 2,
    numericCode: "404",
    grapheme: "KSh",
    template: "$1",
  },
  KGS: {
    decimal: ".",
    thousand: ",",
    code: KGS,
    fraction: 2,
    numericCode: "417",
    grapheme: "\u0441\u043e\u043c",
    template: "1 $",
  },
  KHR: {
    decimal: ".",
    thousand: ",",
    code: KHR,
    fraction: 2,
    numericCode: "116",
    grapheme: "\u17db",
    template: "$1",
  },
  KMF: {
    decimal: ".",
    thousand: ",",
    code: KMF,
    fraction: 0,
    numericCode: "174",
    grapheme: "CF",
    template: "$1",
  },
  KPW: {
    decimal: ".",
    thousand: ",",
    code: KPW,
    fraction: 2,
    numericCode: "408",
    grapheme: "\u20a9",
    template: "$1",
  },
  KRW: {
    decimal: ".",
    thousand: ",",
    code: KRW,
    fraction: 0,
    numericCode: "410",
    grapheme: "\u20a9",
    template: "$1",
  },
  KWD: {
    decimal: ".",
    thousand: ",",
    code: KWD,
    fraction: 3,
    numericCode: "414",
    grapheme: ".\u062f.\u0643",
    template: "1 $",
  },
  KYD: {
    decimal: ".",
    thousand: ",",
    code: KYD,
    fraction: 2,
    numericCode: "136",
    grapheme: "$",
    template: "$1",
  },
  KZT: {
    decimal: ".",
    thousand: ",",
    code: KZT,
    fraction: 2,
    numericCode: "398",
    grapheme: "\u20b8",
    template: "$1",
  },
  LAK: {
    decimal: ".",
    thousand: ",",
    code: LAK,
    fraction: 2,
    numericCode: "418",
    grapheme: "\u20ad",
    template: "$1",
  },
  LBP: {
    decimal: ".",
    thousand: ",",
    code: LBP,
    fraction: 2,
    numericCode: "422",
    grapheme: "\u00a3",
    template: "$1",
  },
  LKR: {
    decimal: ".",
    thousand: ",",
    code: LKR,
    fraction: 2,
    numericCode: "144",
    grapheme: "\u20a8",
    template: "$1",
  },
  LRD: {
    decimal: ".",
    thousand: ",",
    code: LRD,
    fraction: 2,
    numericCode: "430",
    grapheme: "$",
    template: "$1",
  },
  LSL: {
    decimal: ".",
    thousand: ",",
    code: LSL,
    fraction: 2,
    numericCode: "426",
    grapheme: "L",
    template: "$1",
  },
  LYD: {
    decimal: ".",
    thousand: ",",
    code: LYD,
    fraction: 3,
    numericCode: "434",
    grapheme: ".\u062f.\u0644",
    template: "1 $",
  },
  MAD: {
    decimal: ".",
    thousand: ",",
    code: MAD,
    fraction: 2,
    numericCode: "504",
    grapheme: ".\u062f.\u0645",
    template: "1 $",
  },
  MDL: {
    decimal: ".",
    thousand: ",",
    code: MDL,
    fraction: 2,
    numericCode: "498",
    grapheme: "lei",
    template: "1 $",
  },
  MGA: {
    decimal: ".",
    thousand: ",",
    code: MGA,
    fraction: 2,
    numericCode: "969",
    grapheme: "Ar",
    template: "1$",
  },
  MKD: {
    decimal: ".",
    thousand: ",",
    code: MKD,
    fraction: 2,
    numericCode: "807",
    grapheme: "\u0434\u0435\u043d",
    template: "$1",
  },
  MMK: {
    decimal: ".",
    thousand: ",",
    code: MMK,
    fraction: 2,
    numericCode: "104",
    grapheme: "K",
    template: "$1",
  },
  MNT: {
    decimal: ".",
    thousand: ",",
    code: MNT,
    fraction: 2,
    numericCode: "496",
    grapheme: "\u20ae",
    template: "$1",
  },
  MOP: {
    decimal: ".",
    thousand: ",",
    code: MOP,
    fraction: 2,
    numericCode: "446",
    grapheme: "P",
    template: "1 $",
  },
  MRU: {
    decimal: ".",
    thousand: ",",
    code: MRU,
    fraction: 2,
    numericCode: "929",
    grapheme: "UM",
    template: "$1",
  },
  MUR: {
    decimal: ".",
    thousand: ",",
    code: MUR,
    fraction: 2,
    numericCode: "480",
    grapheme: "\u20a8",
    template: "$1",
  },
  MVR: {
    decimal: ".",
    thousand: ",",
    code: MVR,
    fraction: 2,
    numericCode: "462",
    grapheme: "MVR",
    template: "1 $",
  },
  MWK: {
    decimal: ".",
    thousand: ",",
    code: MWK,
    fraction: 2,
    numericCode: "454",
    grapheme: "MK",
    template: "$1",
  },
  MXN: {
    decimal: ".",
    thousand: ",",
    code: MXN,
    fraction: 2,
    numericCode: "484",
    grapheme: "$",
    template: "$1",
  },
  MXV: {
    decimal: ".",
    thousand: ",",
    code: MXV,
    fraction: 2,
    numericCode: "979",
    grapheme: "MXV",
    template: "1 $",
  },
  MYR: {
    decimal: ".",
    thousand: ",",
    code: MYR,
    fraction: 2,
    numericCode: "458",
    grapheme: "RM",
    template: "$1",
  },
  MZN: {
    decimal: ".",
    thousand: ",",
    code: MZN,
    fraction: 2,
    numericCode: "943",
    grapheme: "MT",
    template: "$1",
  },
  NAD: {
    decimal: ".",
    thousand: ",",
    code: NAD,
    fraction: 2,
    numericCode: "516",
    grapheme: "$",
    template: "$1",
  },
  NGN: {
    decimal: ".",
    thousand: ",",
    code: NGN,
    fraction: 2,
    numericCode: "566",
    grapheme: "\u20a6",
    template: "$1",
  },
  NIO: {
    decimal: ".",
    thousand: ",",
    code: NIO,
    fraction: 2,
    numericCode: "558",
    grapheme: "C$",
    template: "$1",
  },
  NOK: {
    decimal: ".",
    thousand: ",",
    code: NOK,
    fraction: 2,
    numericCode: "578",
    grapheme: "kr",
    template: "1 $",
  },
  NPR: {
    decimal: ".",
    thousand: ",",
    code: NPR,
    fraction: 2,
    numericCode: "524",
    grapheme: "\u20a8",
    template: "$1",
  },
  NZD: {
    decimal: ".",
    thousand: ",",
    code: NZD,
    fraction: 2,
    numericCode: "554",
    grapheme: "$",
    template: "$1",
  },
  OMR: {
    decimal: ".",
    thousand: ",",
    code: OMR,
    fraction: 3,
    numericCode: "512",
    grapheme: "\ufdfc",
    template: "1 $",
  },
  PAB: {
    decimal: ".",
    thousand: ",",
    code: PAB,
    fraction: 2,
    numericCode: "590",
    grapheme: "B/.",
    template: "$1",
  },
  PEN: {
    decimal: ".",
    thousand: ",",
    code: PEN,
    fraction: 2,
    numericCode: "604",
    grapheme: "S/",
    template: "$1",
  },
  PGK: {
    decimal: ".",
    thousand: ",",
    code: PGK,
    fraction: 2,
    numericCode: "598",
    grapheme: "K",
    template: "1 $",
  },
  PHP: {
    decimal: ".",
    thousand: ",",
    code: PHP,
    fraction: 2,
    numericCode: "608",
    grapheme: "\u20b1",
    template: "$1",
  },
  PKR: {
    decimal: ".",
    thousand: ",",
    code: PKR,
    fraction: 2,
    numericCode: "586",
    grapheme: "\u20a8",
    template: "$1",
  },
  PLN: {
    decimal: ".",
    thousand: ",",
    code: PLN,
    fraction: 2,
    numericCode: "985",
    grapheme: "z\u0142",
    template: "1 $",
  },
  PYG: {
    decimal: ".",
    thousand: ",",
    code: PYG,
    fraction: 0,
    numericCode: "600",
    grapheme: "Gs",
    template: "1$",
  },
  QAR: {
    decimal: ".",
    thousand: ",",
    code: QAR,
    fraction: 2,
    numericCode: "634",
    grapheme: "\ufdfc",
    template: "1 $",
  },
  RON: {
    decimal: ".",
    thousand: ",",
    code: RON,
    fraction: 2,
    numericCode: "946",
    grapheme: "lei",
    template: "$1",
  },
  RSD: {
    decimal: ".",
    thousand: ",",
    code: RSD,
    fraction: 2,
    numericCode: "941",
    grapheme: "\u0414\u0438\u043d.",
    template: "$1",
  },
  RUB: {
    decimal: ".",
    thousand: ",",
    code: RUB,
    fraction: 2,
    numericCode: "643",
    grapheme: "\u20bd",
    template: "1 $",
  },
  RWF: {
    decimal: ".",
    thousand: ",",
    code: RWF,
    fraction: 0,
    numericCode: "646",
    grapheme: "FRw",
    template: "1 $",
  },
  SAR: {
    decimal: ".",
    thousand: ",",
    code: SAR,
    fraction: 2,
    numericCode: "682",
    grapheme: "\ufdfc",
    template: "1 $",
  },
  SBD: {
    decimal: ".",
    thousand: ",",
    code: SBD,
    fraction: 2,
    numericCode: "090",
    grapheme: "$",
    template: "$1",
  },
  SCR: {
    decimal: ".",
    thousand: ",",
    code: SCR,
    fraction: 2,
    numericCode: "690",
    grapheme: "\u20a8",
    template: "$1",
  },
  SDG: {
    decimal: ".",
    thousand: ",",
    code: SDG,
    fraction: 2,
    numericCode: "938",
    grapheme: "\u00a3",
    template: "$1",
  },
  SEK: {
    decimal: ".",
    thousand: ",",
    code: SEK,
    fraction: 2,
    numericCode: "752",
    grapheme: "kr",
    template: "1 $",
  },
  SGD: {
    decimal: ".",
    thousand: ",",
    code: SGD,
    fraction: 2,
    numericCode: "702",
    grapheme: "S$",
    template: "$1",
  },
  SHP: {
    decimal: ".",
    thousand: ",",
    code: SHP,
    fraction: 2,
    numericCode: "654",
    grapheme: "\u00a3",
    template: "$1",
  },
  SLE: {
    decimal: ".",
    thousand: ",",
    code: SLE,
    fraction: 2,
    numericCode: "925",
    grapheme: "Le",
    template: "1 $",
  },
  SLL: {
    decimal: ".",
    thousand: ",",
    code: SLL,
    fraction: 2,
    numericCode: "694",
    grapheme: "Le",
    template: "1 $",
  },
  SOS: {
    decimal: ".",
    thousand: ",",
    code: SOS,
    fraction: 2,
    numericCode: "706",
    grapheme: "Sh",
    template: "1 $",
  },
  SRD: {
    decimal: ".",
    thousand: ",",
    code: SRD,
    fraction: 2,
    numericCode: "968",
    grapheme: "$",
    template: "$1",
  },
  SSP: {
    decimal: ".",
    thousand: ",",
    code: SSP,
    fraction: 2,
    numericCode: "728",
    grapheme: "\u00a3",
    template: "1 $",
  },
  STN: {
    decimal: ".",
    thousand: ",",
    code: STN,
    fraction: 2,
    numericCode: "930",
    grapheme: "Db",
    template: "1 $",
  },
  SVC: {
    decimal: ".",
    thousand: ",",
    code: SVC,
    fraction: 2,
    numericCode: "222",
    grapheme: "\u20a1",
    template: "$1",
  },
  SYP: {
    decimal: ".",
    thousand: ",",
    code: SYP,
    fraction: 2,
    numericCode: "760",
    grapheme: "\u00a3",
    template: "1 $",
  },
  SZL: {
    decimal: ".",
    thousand: ",",
    code: SZL,
    fraction: 2,
    numericCode: "748",
    grapheme: "\u00a3",
    template: "$1",
  },
  THB: {
    decimal: ".",
    thousand: ",",
    code: THB,
    fraction: 2,
    numericCode: "764",
    grapheme: "\u0e3f",
    template: "$1",
  },
  TJS: {
    decimal: ".",
    thousand: ",",
    code: TJS,
    fraction: 2,
    numericCode: "972",
    grapheme: "SM",
    template: "1 $",
  },
  TMT: {
    decimal: ".",
    thousand: ",",
    code: TMT,
    fraction: 2,
    numericCode: "934",
    grapheme: "T",
    template: "1 $",
  },
  TND: {
    decimal: ".",
    thousand: ",",
    code: TND,
    fraction: 3,
    numericCode: "788",
    grapheme: ".\u062f.\u062a",
    template: "1 $",
  },
  TOP: {
    decimal: ".",
    thousand: ",",
    code: TOP,
    fraction: 2,
    numericCode: "776",
    grapheme: "T$",
    template: "$1",
  },
  TRY: {
    decimal: ".",
    thousand: ",",
    code: TRY,
    fraction: 2,
    numericCode: "949",
    grapheme: "\u20ba",
    template: "$1",
  },
  TTD: {
    decimal: ".",
    thousand: ",",
    code: TTD,
    fraction: 2,
    numericCode: "780",
    grapheme: "TT$",
    template: "$1",
  },
  TWD: {
    decimal: ".",
    thousand: ",",
    code: TWD,
    fraction: 2,
    numericCode: "901",
    grapheme: "NT$",
    template: "$1",
  },
  TZS: {
    decimal: ".",
    thousand: ",",
    code: TZS,
    fraction: 2,
    numericCode: "834",
    grapheme: "TSh",
    template: "$1",
  },
  UAH: {
    decimal: ".",
    thousand: ",",
    code: UAH,
    fraction: 2,
    numericCode: "980",
    grapheme: "\u20b4",
    template: "1 $",
  },
  UGX: {
    decimal: ".",
    thousand: ",",
    code: UGX,
    fraction: 0,
    numericCode: "800",
    grapheme: "USh",
    template: "1 $",
  },
  USD: {
    decimal: ".",
    thousand: ",",
    code: USD,
    fraction: 2,
    numericCode: "840",
    grapheme: "$",
    template: "$1",
  },
  USN: {
    decimal: ".",
    thousand: ",",
    code: USN,
    fraction: 2,
    numericCode: "997",
    grapheme: "US$",
    template: "$1",
  },
  UYI: {
    decimal: ".",
    thousand: ",",
    code: UYI,
    fraction: 0,
    numericCode: "940",
    grapheme: "UYI",
    template: "1 $",
  },
  UYU: {
    decimal: ".",
    thousand: ",",
    code: UYU,
    fraction: 2,
    numericCode: "858",
    grapheme: "$U",
    template: "$1",
  },
  UYW: {
    decimal: ".",
    thousand: ",",
    code: UYW,
    fraction: 4,
    numericCode: "927",
    grapheme: "UYW",
    template: "1 $",
  },
  UZS: {
    decimal: ".",
    thousand: ",",
    code: UZS,
    fraction: 2,
    numericCode: "860",
    grapheme: "so\u2019m",
    template: "$1",
  },
  VES: {
    decimal: ".",
    thousand: ",",
    code: VES,
    fraction: 2,
    numericCode: "928",
    grapheme: "Bs.S",
    template: "$1",
  },
  VND: {
    decimal: ".",
    thousand: ",",
    code: VND,
    fraction: 0,
    numericCode: "704",
    grapheme: "\u20ab",
    template: "1 $",
  },
  VUV: {
    decimal: ".",
    thousand: ",",
    code: VUV,
    fraction: 0,
    numericCode: "548",
    grapheme: "Vt",
    template: "$1",
  },
  WST: {
    decimal: ".",
    thousand: ",",
    code: WST,
    fraction: 2,
    numericCode: "882",
    grapheme: "T",
    template: "1 $",
  },
  XAF: {
    decimal: ".",
    thousand: ",",
    code: XAF,
    fraction: 0,
    numericCode: "950",
    grapheme: "Fr",
    template: "1 $",
  },
  XAG: {
    decimal: ".",
    thousand: ",",
    code: XAG,
    fraction: 0,
    numericCode: "961",
    grapheme: "oz t",
    template: "1 $",
  },
  XAU: {
    decimal: ".",
    thousand: ",",
    code: XAU,
    fraction: 0,
    numericCode: "959",
    grapheme: "oz t",
    template: "1 $",
  },
  XBA: {
    decimal: ".",
    thousand: ",",
    code: XBA,
    fraction: 0,
    numericCode: "955",
    grapheme: "XBA",
    template: "1 $",
  },
  XBB: {
    decimal: ".",
    thousand: ",",
    code: XBB,
    fraction: 0,
    numericCode: "956",
    grapheme: "XBB",
    template: "1 $",
  },
  XBC: {
    decimal: ".",
    thousand: ",",
    code: XBC,
    fraction: 0,
    numericCode: "957",
    grapheme: "XBC",
    template: "1 $",
  },
  XBD: {
    decimal: ".",
    thousand: ",",
    code: XBD,
    fraction: 0,
    numericCode: "958",
    grapheme: "XBD",
    template: "1 $",
  },
  XCD: {
    decimal: ".",
    thousand: ",",
    code: XCD,
    fraction: 2,
    numericCode: "951",
    grapheme: "$",
    template: "$1",
  },
  XDR: {
    decimal: ".",
    thousand: ",",
    code: XDR,
    fraction: 0,
    numericCode: "960",
    grapheme: "SDR",
    template: "1 $",
  },
  XOF: {
    decimal: ".",
    thousand: ",",
    code: XOF,
    fraction: 0,
    numericCode: "952",
    grapheme: "CFA",
    template: "1 $",
  },
  XPD: {
    decimal: ".",
    thousand: ",",
    code: XPD,
    fraction: 0,
    numericCode: "964",
    grapheme: "oz t",
    template: "1 $",
  },
  XPF: {
    decimal: ".",
    thousand: ",",
    code: XPF,
    fraction: 0,
    numericCode: "953",
    grapheme: "CFP",
    template: "1 $",
  },
  XPT: {
    decimal: ".",
    thousand: ",",
    code: XPT,
    fraction: 0,
    numericCode: "962",
    grapheme: "oz t",
    template: "1 $",
  },
  XSU: {
    decimal: ".",
    thousand: ",",
    code: XSU,
    fraction: 0,
    numericCode: "994",
    grapheme: "XSU",
    template: "1 $",
  },
  XTS: {
    decimal: ".",
    thousand: ",",
    code: XTS,
    fraction: 0,
    numericCode: "963",
    grapheme: "XTS",
    template: "1 $",
  },
  XUA: {
    decimal: ".",
    thousand: ",",
    code: XUA,
    fraction: 0,
    numericCode: "965",
    grapheme: "XUA",
    template: "1 $",
  },
  XXX: {
    decimal: ".",
    thousand: ",",
    code: XXX,
    fraction: 0,
    numericCode: "999",
    grapheme: "XXX",
    template: "1 $",
  },
  YER: {
    decimal: ".",
    thousand: ",",
    code: YER,
    fraction: 2,
    numericCode: "886",
    grapheme: "\ufdfc",
    template: "1 $",
  },
  ZAR: {
    decimal: ".",
    thousand: ",",
    code: ZAR,
    fraction: 2,
    numericCode: "710",
    grapheme: "R",
    template: "$1",
  },
  ZMW: {
    decimal: ".",
    thousand: ",",
    code: ZMW,
    fraction: 2,
    numericCode: "967",
    grapheme: "ZK",
    template: "$1",
  },
  ZWL: {
    decimal: ".",
    thousand: ",",
    code: ZWL,
    fraction: 2,
    numericCode: "932",
    grapheme: "Z$",
    template: "$1",
  },
} as const;
