default: database
connections:
  sync:
    driver: sync
  database:
    driver: database
    table: jobs
    queue: default
    retry_after: 90
  null:
    driver: null
failed:
  driver: database-uuids
  table: failed_jobs
