driver: database
lifetime: 120
expire_on_close: false
encrypt: false
files: storage/framework/sessions
connection: ""
table: sessions
store: ""
lottery:
  - 2
  - 100
cookie: bedrock-session
path: /
domain: ""
secure: false
http_only: true
same_site: lax
partitioned: false
